// Libretro cores available per platform (from buildbot.libretro.com)
export const PLATFORM_CORES: Record<string, string[]> = {
  SNES: ["snes9x", "bsnes", "bsnes2014_accuracy", "bsnes2014_balanced"],
  NES: ["nestopia", "fceumm", "quicknes", "mesen"],
  N64: ["mupen64plus_next"],
  GBA: ["mgba", "mgba2015", "vbam"],
  GBC: ["gambatte", "sameboy", "gearboy", "mgba"],
  GB: ["gambatte", "sameboy", "gearboy", "mgba"],
  NDS: ["melonds", "melondsds", "desmume"],
  "3DS": ["citra", "lime3ds"],
  GAMECUBE: ["dolphin"],
  MEGA_DRIVE: ["genesis_plus_gx", "picodrive", "blastem"],
  SMS: ["smsplus", "gearsystem", "picodrive"],
  GAME_GEAR: ["gearsystem", "genesis_plus_gx"],
  PCE: ["mednafen_pce_fast", "turbo2013"],
  "32X": ["picodrive"],
  PS1: ["pcsx_rearmed", "SwanStation"],
  PS2: ["pcsx2", "play"],
  PS3: ["rpcs3"],
  PSP: ["ppsspp"],
  MAME: ["fbneo", "mame", "mame2003_plus", "mame2010"],
  NEOGEO: ["fbneo", "fbalpha2012_neogeo", "geolith"],
  NGP: ["mednafen_ngp"],
  LYNX: ["mednafen_lynx"],
  WSWAN: ["mednafen_wswan"],
  COLECOVISION: ["gearcoleco"],
  VB: ["mednafen_vb"],
  PC: ["pc"],
};
