use super::libretro::GameMetadata;

pub struct ArcadeDriverEntry {
    pub driver: &'static str,
    pub display_name: &'static str,
    pub genre: &'static str,
    pub developer: &'static str,
    pub publisher: &'static str,
    pub release_year: i32,
    pub franchise: Option<&'static str>,
}

pub static ARCADE_DRIVERS: &[ArcadeDriverEntry] = &[
    // --- Capcom Classics & CPS1 / CPS2 ---
    ArcadeDriverEntry {
        driver: "dino",
        display_name: "Cadillacs and Dinosaurs",
        genre: "Beat 'em up / Acción",
        developer: "Capcom",
        publisher: "Capcom",
        release_year: 1993,
        franchise: None,
    },
    ArcadeDriverEntry {
        driver: "knights",
        display_name: "Knights of the Round",
        genre: "Beat 'em up / Acción",
        developer: "Capcom",
        publisher: "Capcom",
        release_year: 1991,
        franchise: None,
    },
    ArcadeDriverEntry {
        driver: "kod",
        display_name: "The King of Dragons",
        genre: "Beat 'em up / Acción",
        developer: "Capcom",
        publisher: "Capcom",
        release_year: 1991,
        franchise: None,
    },
    ArcadeDriverEntry {
        driver: "ffight",
        display_name: "Final Fight",
        genre: "Beat 'em up / Acción",
        developer: "Capcom",
        publisher: "Capcom",
        release_year: 1989,
        franchise: Some("Final Fight"),
    },
    ArcadeDriverEntry {
        driver: "captcomm",
        display_name: "Captain Commando",
        genre: "Beat 'em up / Acción",
        developer: "Capcom",
        publisher: "Capcom",
        release_year: 1991,
        franchise: Some("Captain Commando"),
    },
    ArcadeDriverEntry {
        driver: "punisher",
        display_name: "The Punisher",
        genre: "Beat 'em up / Acción",
        developer: "Capcom",
        publisher: "Capcom",
        release_year: 1993,
        franchise: Some("Marvel"),
    },
    ArcadeDriverEntry {
        driver: "avsp",
        display_name: "Alien vs. Predator",
        genre: "Beat 'em up / Acción",
        developer: "Capcom",
        publisher: "Capcom",
        release_year: 1994,
        franchise: Some("Alien vs. Predator"),
    },
    ArcadeDriverEntry {
        driver: "ddtod",
        display_name: "Dungeons & Dragons: Tower of Doom",
        genre: "Beat 'em up / Rol",
        developer: "Capcom",
        publisher: "Capcom",
        release_year: 1993,
        franchise: Some("Dungeons & Dragons"),
    },
    ArcadeDriverEntry {
        driver: "ddsom",
        display_name: "Dungeons & Dragons: Shadow over Mystara",
        genre: "Beat 'em up / Rol",
        developer: "Capcom",
        publisher: "Capcom",
        release_year: 1996,
        franchise: Some("Dungeons & Dragons"),
    },
    ArcadeDriverEntry {
        driver: "sf2",
        display_name: "Street Fighter II: The World Warrior",
        genre: "Lucha / Fighting",
        developer: "Capcom",
        publisher: "Capcom",
        release_year: 1991,
        franchise: Some("Street Fighter"),
    },
    ArcadeDriverEntry {
        driver: "sf2ce",
        display_name: "Street Fighter II': Champion Edition",
        genre: "Lucha / Fighting",
        developer: "Capcom",
        publisher: "Capcom",
        release_year: 1992,
        franchise: Some("Street Fighter"),
    },
    ArcadeDriverEntry {
        driver: "sf2hf",
        display_name: "Street Fighter II': Hyper Fighting",
        genre: "Lucha / Fighting",
        developer: "Capcom",
        publisher: "Capcom",
        release_year: 1992,
        franchise: Some("Street Fighter"),
    },
    ArcadeDriverEntry {
        driver: "ssf2",
        display_name: "Super Street Fighter II: The New Challengers",
        genre: "Lucha / Fighting",
        developer: "Capcom",
        publisher: "Capcom",
        release_year: 1993,
        franchise: Some("Street Fighter"),
    },
    ArcadeDriverEntry {
        driver: "ssf2t",
        display_name: "Super Street Fighter II Turbo",
        genre: "Lucha / Fighting",
        developer: "Capcom",
        publisher: "Capcom",
        release_year: 1994,
        franchise: Some("Street Fighter"),
    },
    ArcadeDriverEntry {
        driver: "mvc",
        display_name: "Marvel vs. Capcom: Clash of Super Heroes",
        genre: "Lucha / Fighting",
        developer: "Capcom",
        publisher: "Capcom",
        release_year: 1998,
        franchise: Some("Marvel vs. Capcom"),
    },
    ArcadeDriverEntry {
        driver: "xmvsf",
        display_name: "X-Men vs. Street Fighter",
        genre: "Lucha / Fighting",
        developer: "Capcom",
        publisher: "Capcom",
        release_year: 1996,
        franchise: Some("Marvel vs. Capcom"),
    },
    ArcadeDriverEntry {
        driver: "mshvsf",
        display_name: "Marvel Super Heroes vs. Street Fighter",
        genre: "Lucha / Fighting",
        developer: "Capcom",
        publisher: "Capcom",
        release_year: 1997,
        franchise: Some("Marvel vs. Capcom"),
    },
    ArcadeDriverEntry {
        driver: "strider",
        display_name: "Strider",
        genre: "Plataformas / Acción",
        developer: "Capcom",
        publisher: "Capcom",
        release_year: 1989,
        franchise: Some("Strider"),
    },
    ArcadeDriverEntry {
        driver: "gng",
        display_name: "Ghosts 'n Goblins",
        genre: "Plataformas / Acción",
        developer: "Capcom",
        publisher: "Capcom",
        release_year: 1985,
        franchise: Some("Ghosts 'n Goblins"),
    },
    ArcadeDriverEntry {
        driver: "ghouls",
        display_name: "Ghouls 'n Ghosts",
        genre: "Plataformas / Acción",
        developer: "Capcom",
        publisher: "Capcom",
        release_year: 1988,
        franchise: Some("Ghosts 'n Goblins"),
    },
    ArcadeDriverEntry {
        driver: "1942",
        display_name: "1942",
        genre: "Shooter / Shoot 'em up",
        developer: "Capcom",
        publisher: "Capcom",
        release_year: 1984,
        franchise: Some("1942"),
    },
    ArcadeDriverEntry {
        driver: "1943",
        display_name: "1943: The Battle of Midway",
        genre: "Shooter / Shoot 'em up",
        developer: "Capcom",
        publisher: "Capcom",
        release_year: 1987,
        franchise: Some("1942"),
    },
    ArcadeDriverEntry {
        driver: "1944",
        display_name: "1944: The Loop Master",
        genre: "Shooter / Shoot 'em up",
        developer: "Raizing / Capcom",
        publisher: "Capcom",
        release_year: 2000,
        franchise: Some("1942"),
    },
    ArcadeDriverEntry {
        driver: "19xx",
        display_name: "19XX: The War Against Destiny",
        genre: "Shooter / Shoot 'em up",
        developer: "Capcom",
        publisher: "Capcom",
        release_year: 1996,
        franchise: Some("1942"),
    },
    ArcadeDriverEntry {
        driver: "progear",
        display_name: "Progear no Arashi",
        genre: "Shooter / Shoot 'em up",
        developer: "Cave",
        publisher: "Capcom",
        release_year: 2001,
        franchise: None,
    },

    // --- SNK & Neo-Geo Classics ---
    ArcadeDriverEntry {
        driver: "mslug",
        display_name: "Metal Slug: Super Vehicle-001",
        genre: "Shooter Run & Gun",
        developer: "Nazca Corporation",
        publisher: "SNK",
        release_year: 1996,
        franchise: Some("Metal Slug"),
    },
    ArcadeDriverEntry {
        driver: "mslug2",
        display_name: "Metal Slug 2: Super Vehicle-001/II",
        genre: "Shooter Run & Gun",
        developer: "SNK",
        publisher: "SNK",
        release_year: 1998,
        franchise: Some("Metal Slug"),
    },
    ArcadeDriverEntry {
        driver: "mslugx",
        display_name: "Metal Slug X",
        genre: "Shooter Run & Gun",
        developer: "SNK",
        publisher: "SNK",
        release_year: 1999,
        franchise: Some("Metal Slug"),
    },
    ArcadeDriverEntry {
        driver: "mslug3",
        display_name: "Metal Slug 3",
        genre: "Shooter Run & Gun",
        developer: "SNK",
        publisher: "SNK",
        release_year: 2000,
        franchise: Some("Metal Slug"),
    },
    ArcadeDriverEntry {
        driver: "mslug4",
        display_name: "Metal Slug 4",
        genre: "Shooter Run & Gun",
        developer: "Mega Enterprise / Noise Factory",
        publisher: "Playmore / SNK",
        release_year: 2002,
        franchise: Some("Metal Slug"),
    },
    ArcadeDriverEntry {
        driver: "mslug5",
        display_name: "Metal Slug 5",
        genre: "Shooter Run & Gun",
        developer: "SNK Playmore",
        publisher: "SNK Playmore",
        release_year: 2003,
        franchise: Some("Metal Slug"),
    },
    ArcadeDriverEntry {
        driver: "kof94",
        display_name: "The King of Fighters '94",
        genre: "Lucha / Fighting",
        developer: "SNK",
        publisher: "SNK",
        release_year: 1994,
        franchise: Some("The King of Fighters"),
    },
    ArcadeDriverEntry {
        driver: "kof95",
        display_name: "The King of Fighters '95",
        genre: "Lucha / Fighting",
        developer: "SNK",
        publisher: "SNK",
        release_year: 1995,
        franchise: Some("The King of Fighters"),
    },
    ArcadeDriverEntry {
        driver: "kof96",
        display_name: "The King of Fighters '96",
        genre: "Lucha / Fighting",
        developer: "SNK",
        publisher: "SNK",
        release_year: 1996,
        franchise: Some("The King of Fighters"),
    },
    ArcadeDriverEntry {
        driver: "kof97",
        display_name: "The King of Fighters '97",
        genre: "Lucha / Fighting",
        developer: "SNK",
        publisher: "SNK",
        release_year: 1997,
        franchise: Some("The King of Fighters"),
    },
    ArcadeDriverEntry {
        driver: "kof98",
        display_name: "The King of Fighters '98: The Slugfest",
        genre: "Lucha / Fighting",
        developer: "SNK",
        publisher: "SNK",
        release_year: 1998,
        franchise: Some("The King of Fighters"),
    },
    ArcadeDriverEntry {
        driver: "kof99",
        display_name: "The King of Fighters '99: Millennium Battle",
        genre: "Lucha / Fighting",
        developer: "SNK",
        publisher: "SNK",
        release_year: 1999,
        franchise: Some("The King of Fighters"),
    },
    ArcadeDriverEntry {
        driver: "kof2000",
        display_name: "The King of Fighters 2000",
        genre: "Lucha / Fighting",
        developer: "SNK",
        publisher: "SNK",
        release_year: 2000,
        franchise: Some("The King of Fighters"),
    },
    ArcadeDriverEntry {
        driver: "kof2001",
        display_name: "The King of Fighters 2001",
        genre: "Lucha / Fighting",
        developer: "Eolith / BrezzaSoft",
        publisher: "Sun Amusement",
        release_year: 2001,
        franchise: Some("The King of Fighters"),
    },
    ArcadeDriverEntry {
        driver: "kof2002",
        display_name: "The King of Fighters 2002: Challenge to Ultimate Battle",
        genre: "Lucha / Fighting",
        developer: "Eolith",
        publisher: "Playmore",
        release_year: 2002,
        franchise: Some("The King of Fighters"),
    },
    ArcadeDriverEntry {
        driver: "kof2003",
        display_name: "The King of Fighters 2003",
        genre: "Lucha / Fighting",
        developer: "SNK Playmore",
        publisher: "SNK Playmore",
        release_year: 2003,
        franchise: Some("The King of Fighters"),
    },
    ArcadeDriverEntry {
        driver: "lastblad",
        display_name: "The Last Blade",
        genre: "Lucha / Fighting",
        developer: "SNK",
        publisher: "SNK",
        release_year: 1997,
        franchise: Some("The Last Blade"),
    },
    ArcadeDriverEntry {
        driver: "lastbld2",
        display_name: "The Last Blade 2",
        genre: "Lucha / Fighting",
        developer: "SNK",
        publisher: "SNK",
        release_year: 1998,
        franchise: Some("The Last Blade"),
    },
    ArcadeDriverEntry {
        driver: "garou",
        display_name: "Garou: Mark of the Wolves",
        genre: "Lucha / Fighting",
        developer: "SNK",
        publisher: "SNK",
        release_year: 1999,
        franchise: Some("Fatal Fury"),
    },
    ArcadeDriverEntry {
        driver: "fatfury",
        display_name: "Fatal Fury: King of Fighters",
        genre: "Lucha / Fighting",
        developer: "SNK",
        publisher: "SNK",
        release_year: 1991,
        franchise: Some("Fatal Fury"),
    },
    ArcadeDriverEntry {
        driver: "fatfury2",
        display_name: "Fatal Fury 2",
        genre: "Lucha / Fighting",
        developer: "SNK",
        publisher: "SNK",
        release_year: 1992,
        franchise: Some("Fatal Fury"),
    },
    ArcadeDriverEntry {
        driver: "fatfurys",
        display_name: "Fatal Fury Special",
        genre: "Lucha / Fighting",
        developer: "SNK",
        publisher: "SNK",
        release_year: 1993,
        franchise: Some("Fatal Fury"),
    },
    ArcadeDriverEntry {
        driver: "rbff1",
        display_name: "Real Bout Fatal Fury",
        genre: "Lucha / Fighting",
        developer: "SNK",
        publisher: "SNK",
        release_year: 1995,
        franchise: Some("Fatal Fury"),
    },
    ArcadeDriverEntry {
        driver: "rbff2",
        display_name: "Real Bout Fatal Fury 2: The Newcomers",
        genre: "Lucha / Fighting",
        developer: "SNK",
        publisher: "SNK",
        release_year: 1998,
        franchise: Some("Fatal Fury"),
    },
    ArcadeDriverEntry {
        driver: "samsho",
        display_name: "Samurai Shodown",
        genre: "Lucha / Fighting",
        developer: "SNK",
        publisher: "SNK",
        release_year: 1993,
        franchise: Some("Samurai Shodown"),
    },
    ArcadeDriverEntry {
        driver: "samsho2",
        display_name: "Samurai Shodown II",
        genre: "Lucha / Fighting",
        developer: "SNK",
        publisher: "SNK",
        release_year: 1994,
        franchise: Some("Samurai Shodown"),
    },
    ArcadeDriverEntry {
        driver: "samsho3",
        display_name: "Samurai Shodown III: Blades of Blood",
        genre: "Lucha / Fighting",
        developer: "SNK",
        publisher: "SNK",
        release_year: 1995,
        franchise: Some("Samurai Shodown"),
    },
    ArcadeDriverEntry {
        driver: "samsho4",
        display_name: "Samurai Shodown IV: Amakusa's Revenge",
        genre: "Lucha / Fighting",
        developer: "SNK",
        publisher: "SNK",
        release_year: 1996,
        franchise: Some("Samurai Shodown"),
    },
    ArcadeDriverEntry {
        driver: "samsho5",
        display_name: "Samurai Shodown V",
        genre: "Lucha / Fighting",
        developer: "Yuki Enterprise",
        publisher: "SNK Playmore",
        release_year: 2003,
        franchise: Some("Samurai Shodown"),
    },
    ArcadeDriverEntry {
        driver: "aof",
        display_name: "Art of Fighting",
        genre: "Lucha / Fighting",
        developer: "SNK",
        publisher: "SNK",
        release_year: 1992,
        franchise: Some("Art of Fighting"),
    },
    ArcadeDriverEntry {
        driver: "aof2",
        display_name: "Art of Fighting 2",
        genre: "Lucha / Fighting",
        developer: "SNK",
        publisher: "SNK",
        release_year: 1994,
        franchise: Some("Art of Fighting"),
    },
    ArcadeDriverEntry {
        driver: "aof3",
        display_name: "Art of Fighting 3: The Path of the Warrior",
        genre: "Lucha / Fighting",
        developer: "SNK",
        publisher: "SNK",
        release_year: 1996,
        franchise: Some("Art of Fighting"),
    },
    ArcadeDriverEntry {
        driver: "blazstar",
        display_name: "Blazing Star",
        genre: "Shooter / Shoot 'em up",
        developer: "Yumekobo",
        publisher: "SNK",
        release_year: 1998,
        franchise: None,
    },
    ArcadeDriverEntry {
        driver: "sengoku3",
        display_name: "Sengoku 3",
        genre: "Beat 'em up / Acción",
        developer: "Noise Factory",
        publisher: "SNK",
        release_year: 2001,
        franchise: Some("Sengoku"),
    },
    ArcadeDriverEntry {
        driver: "shocktro",
        display_name: "Shock Troopers",
        genre: "Shooter Run & Gun",
        developer: "Saurus",
        publisher: "SNK",
        release_year: 1997,
        franchise: Some("Shock Troopers"),
    },
    ArcadeDriverEntry {
        driver: "shocktr2",
        display_name: "Shock Troopers: 2nd Squad",
        genre: "Shooter Run & Gun",
        developer: "Saurus",
        publisher: "SNK",
        release_year: 1998,
        franchise: Some("Shock Troopers"),
    },
    ArcadeDriverEntry {
        driver: "wjammers",
        display_name: "Windjammers",
        genre: "Deportes / Arcade",
        developer: "Data East",
        publisher: "SNK",
        release_year: 1994,
        franchise: Some("Windjammers"),
    },
    ArcadeDriverEntry {
        driver: "neodrift",
        display_name: "Neo Drift Out: New Technology",
        genre: "Carreras / Racing",
        developer: "Visco",
        publisher: "SNK",
        release_year: 1996,
        franchise: Some("Drift Out"),
    },
    ArcadeDriverEntry {
        driver: "tophuntr",
        display_name: "Top Hunter: Roddy & Cathy",
        genre: "Plataformas / Beat 'em up",
        developer: "SNK",
        publisher: "SNK",
        release_year: 1994,
        franchise: None,
    },
    ArcadeDriverEntry {
        driver: "superspy",
        display_name: "The Super Spy",
        genre: "Acción / Disparos",
        developer: "SNK",
        publisher: "SNK",
        release_year: 1990,
        franchise: None,
    },
    ArcadeDriverEntry {
        driver: "pbobblen",
        display_name: "Puzzle Bobble",
        genre: "Puzle",
        developer: "Taito",
        publisher: "SNK",
        release_year: 1994,
        franchise: Some("Bubble Bobble"),
    },
    ArcadeDriverEntry {
        driver: "svc",
        display_name: "SNK vs. Capcom: SVC Chaos",
        genre: "Lucha / Fighting",
        developer: "SNK Playmore",
        publisher: "Playmore",
        release_year: 2003,
        franchise: Some("SNK vs. Capcom"),
    },
    ArcadeDriverEntry {
        driver: "neogeo",
        display_name: "Neo Geo MVS System",
        genre: "Arcade / BIOS",
        developer: "SNK",
        publisher: "SNK",
        release_year: 1990,
        franchise: None,
    },

    // --- Konami, Sega, Namco, Midway & Rare Classics ---
    ArcadeDriverEntry {
        driver: "ssriders",
        display_name: "Sunset Riders",
        genre: "Shooter Run & Gun",
        developer: "Konami",
        publisher: "Konami",
        release_year: 1991,
        franchise: Some("Sunset Riders"),
    },
    ArcadeDriverEntry {
        driver: "tmnt",
        display_name: "Teenage Mutant Ninja Turtles",
        genre: "Beat 'em up / Acción",
        developer: "Konami",
        publisher: "Konami",
        release_year: 1989,
        franchise: Some("TMNT"),
    },
    ArcadeDriverEntry {
        driver: "tmnt2",
        display_name: "Teenage Mutant Ninja Turtles: Turtles in Time",
        genre: "Beat 'em up / Acción",
        developer: "Konami",
        publisher: "Konami",
        release_year: 1991,
        franchise: Some("TMNT"),
    },
    ArcadeDriverEntry {
        driver: "simpsons",
        display_name: "The Simpsons",
        genre: "Beat 'em up / Acción",
        developer: "Konami",
        publisher: "Konami",
        release_year: 1991,
        franchise: Some("The Simpsons"),
    },
    ArcadeDriverEntry {
        driver: "xmen",
        display_name: "X-Men",
        genre: "Beat 'em up / Acción",
        developer: "Konami",
        publisher: "Konami",
        release_year: 1992,
        franchise: Some("X-Men"),
    },
    ArcadeDriverEntry {
        driver: "kinst",
        display_name: "Killer Instinct",
        genre: "Lucha / Fighting",
        developer: "Rare",
        publisher: "Nintendo / Midway",
        release_year: 1994,
        franchise: Some("Killer Instinct"),
    },
    ArcadeDriverEntry {
        driver: "kinst2",
        display_name: "Killer Instinct 2",
        genre: "Lucha / Fighting",
        developer: "Rare",
        publisher: "Nintendo / Midway",
        release_year: 1996,
        franchise: Some("Killer Instinct"),
    },
    ArcadeDriverEntry {
        driver: "goldnaxe",
        display_name: "Golden Axe",
        genre: "Beat 'em up / Acción",
        developer: "Sega",
        publisher: "Sega",
        release_year: 1989,
        franchise: Some("Golden Axe"),
    },
    ArcadeDriverEntry {
        driver: "souledge",
        display_name: "Soul Edge",
        genre: "Lucha / Fighting",
        developer: "Namco",
        publisher: "Namco",
        release_year: 1995,
        franchise: Some("Soulcalibur"),
    },
    ArcadeDriverEntry {
        driver: "numanath",
        display_name: "Numan Athletics",
        genre: "Deportes / Arcade",
        developer: "Namco",
        publisher: "Namco",
        release_year: 1993,
        franchise: None,
    },
    ArcadeDriverEntry {
        driver: "pacman",
        display_name: "Pac-Man",
        genre: "Arcade / Laberinto",
        developer: "Namco",
        publisher: "Namco / Midway",
        release_year: 1980,
        franchise: Some("Pac-Man"),
    },
    ArcadeDriverEntry {
        driver: "mspacman",
        display_name: "Ms. Pac-Man",
        genre: "Arcade / Laberinto",
        developer: "General Computer / Midway",
        publisher: "Midway",
        release_year: 1982,
        franchise: Some("Pac-Man"),
    },
    ArcadeDriverEntry {
        driver: "galaga",
        display_name: "Galaga",
        genre: "Shooter / Shoot 'em up",
        developer: "Namco",
        publisher: "Namco / Midway",
        release_year: 1981,
        franchise: Some("Galaga"),
    },
    ArcadeDriverEntry {
        driver: "dkong",
        display_name: "Donkey Kong",
        genre: "Plataformas / Arcade",
        developer: "Nintendo",
        publisher: "Nintendo",
        release_year: 1981,
        franchise: Some("Donkey Kong"),
    },
];

pub fn resolve_arcade_driver(raw_name: &str) -> Option<GameMetadata> {
    let stem = std::path::Path::new(raw_name)
        .file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or(raw_name)
        .to_lowercase();

    let clean_driver = stem.split(|c: char| !c.is_alphanumeric()).next().unwrap_or(&stem);

    for entry in ARCADE_DRIVERS {
        if entry.driver.eq_ignore_ascii_case(clean_driver)
            || entry.driver.eq_ignore_ascii_case(&stem)
            || entry.display_name.eq_ignore_ascii_case(raw_name)
            || entry.display_name.to_lowercase() == stem
        {
            return Some(GameMetadata {
                display_name: Some(entry.display_name.to_string()),
                release_year: Some(entry.release_year),
                release_month: None,
                developer: Some(entry.developer.to_string()),
                publisher: Some(entry.publisher.to_string()),
                genre: Some(entry.genre.to_string()),
                franchise: entry.franchise.map(|f| f.to_string()),
                region: Some("World".to_string()),
                rating: None,
            });
        }
    }

    None
}
