use super::libretro::GameMetadata;

pub struct CuratedMetaEntry {
    pub platforms: &'static [&'static str],
    pub keys: &'static [&'static str],
    pub display_name: &'static str,
    pub genre: &'static str,
    pub developer: &'static str,
    pub publisher: &'static str,
    pub release_year: i32,
    pub franchise: Option<&'static str>,
}

pub static CURATED_CATALOG: &[CuratedMetaEntry] = &[
    // --- POKEMON CLÁSICOS (GB, GBC, GBA, NDS) ---
    CuratedMetaEntry {
        platforms: &["GB"],
        keys: &[
            "pokemon - edicion roja",
            "pokemon red",
            "pokemon - red version",
            "pokemon roja",
        ],
        display_name: "Pokémon Edición Roja",
        genre: "Rol / RPG",
        developer: "Game Freak",
        publisher: "Nintendo",
        release_year: 1996,
        franchise: Some("Pokemon"),
    },
    CuratedMetaEntry {
        platforms: &["GB"],
        keys: &[
            "pokemon - edicion azul",
            "pokemon blue",
            "pokemon - blue version",
            "pokemon azul",
        ],
        display_name: "Pokémon Edición Azul",
        genre: "Rol / RPG",
        developer: "Game Freak",
        publisher: "Nintendo",
        release_year: 1996,
        franchise: Some("Pokemon"),
    },
    CuratedMetaEntry {
        platforms: &["GBC"],
        keys: &[
            "pokemon - gold version",
            "pokemon gold",
            "pokemon oro",
            "pokemon - edicion oro",
        ],
        display_name: "Pokémon Edición Oro",
        genre: "Rol / RPG",
        developer: "Game Freak",
        publisher: "Nintendo",
        release_year: 1999,
        franchise: Some("Pokemon"),
    },
    CuratedMetaEntry {
        platforms: &["GBC"],
        keys: &[
            "pokemon - silver version",
            "pokemon silver",
            "pokemon plata",
            "pokemon - edicion plata",
        ],
        display_name: "Pokémon Edición Plata",
        genre: "Rol / RPG",
        developer: "Game Freak",
        publisher: "Nintendo",
        release_year: 1999,
        franchise: Some("Pokemon"),
    },
    CuratedMetaEntry {
        platforms: &["GBA"],
        keys: &[
            "pokemon - edicion esmeralda",
            "pokemon emerald",
            "pokemon esmeralda",
        ],
        display_name: "Pokémon Edición Esmeralda",
        genre: "Rol / RPG",
        developer: "Game Freak",
        publisher: "Nintendo",
        release_year: 2004,
        franchise: Some("Pokemon"),
    },
    CuratedMetaEntry {
        platforms: &["GBA"],
        keys: &["pokemon - edicion rubi", "pokemon ruby", "pokemon rubi"],
        display_name: "Pokémon Edición Rubí",
        genre: "Rol / RPG",
        developer: "Game Freak",
        publisher: "Nintendo",
        release_year: 2002,
        franchise: Some("Pokemon"),
    },
    CuratedMetaEntry {
        platforms: &["GBA"],
        keys: &[
            "pokemon - edicion zafiro",
            "pokemon sapphire",
            "pokemon zafiro",
        ],
        display_name: "Pokémon Edición Zafiro",
        genre: "Rol / RPG",
        developer: "Game Freak",
        publisher: "Nintendo",
        release_year: 2002,
        franchise: Some("Pokemon"),
    },
    CuratedMetaEntry {
        platforms: &["GBA"],
        keys: &[
            "pokemon - edicion rojo fuego",
            "pokemon firered",
            "pokemon rojo fuego",
        ],
        display_name: "Pokémon Edición Rojo Fuego",
        genre: "Rol / RPG",
        developer: "Game Freak",
        publisher: "Nintendo",
        release_year: 2004,
        franchise: Some("Pokemon"),
    },
    CuratedMetaEntry {
        platforms: &["GBA"],
        keys: &[
            "pokemon - edicion verde hoja",
            "pokemon leafgreen",
            "pokemon verde hoja",
        ],
        display_name: "Pokémon Edición Verde Hoja",
        genre: "Rol / RPG",
        developer: "Game Freak",
        publisher: "Nintendo",
        release_year: 2004,
        franchise: Some("Pokemon"),
    },
    CuratedMetaEntry {
        platforms: &["GBA"],
        keys: &[
            "pokemon mystery dungeon - red rescue team",
            "red rescue team",
            "equipo de rescate rojo",
        ],
        display_name: "Pokémon Mundo Misterioso: Equipo de Rescate Rojo",
        genre: "Rol / RPG",
        developer: "Spike Chunsoft",
        publisher: "Nintendo",
        release_year: 2005,
        franchise: Some("Pokemon"),
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &[
            "pokemon - edicion platino",
            "pokemon platinum",
            "pokemon platino",
        ],
        display_name: "Pokémon Edición Platino",
        genre: "Rol / RPG",
        developer: "Game Freak",
        publisher: "The Pokémon Company / Nintendo",
        release_year: 2008,
        franchise: Some("Pokemon"),
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["pokemon conquest", "pokemon + nobunaga"],
        display_name: "Pokémon Conquest",
        genre: "Estrategia",
        developer: "Tecmo Koei",
        publisher: "The Pokémon Company / Nintendo",
        release_year: 2012,
        franchise: Some("Pokemon"),
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &[
            "dragon quest ix - sentinels of the starry skies",
            "dragon quest ix",
            "sentinels of the starry skies",
        ],
        display_name: "Dragon Quest IX: Centinelas del Firmamento",
        genre: "Rol / RPG",
        developer: "Level-5 / Square Enix",
        publisher: "Nintendo",
        release_year: 2009,
        franchise: Some("Dragon Quest"),
    },
    // --- GBA JOJAS ---
    CuratedMetaEntry {
        platforms: &["GBA"],
        keys: &["advance wars 2 - black hole rising", "advance wars 2"],
        display_name: "Advance Wars 2: Black Hole Rising",
        genre: "Estrategia",
        developer: "Intelligent Systems",
        publisher: "Nintendo",
        release_year: 2003,
        franchise: Some("Advance Wars"),
    },
    CuratedMetaEntry {
        platforms: &["GBA"],
        keys: &[
            "golden sun - the lost age",
            "golden sun 2",
            "la edad perdida",
        ],
        display_name: "Golden Sun: La Edad Perdida",
        genre: "Rol / RPG",
        developer: "Camelot Software Planning",
        publisher: "Nintendo",
        release_year: 2002,
        franchise: Some("Golden Sun"),
    },
    CuratedMetaEntry {
        platforms: &["GBA"],
        keys: &["golden sun"],
        display_name: "Golden Sun",
        genre: "Rol / RPG",
        developer: "Camelot Software Planning",
        publisher: "Nintendo",
        release_year: 2001,
        franchise: Some("Golden Sun"),
    },
    CuratedMetaEntry {
        platforms: &["GBA"],
        keys: &[
            "zelda - the minish cap",
            "the minish cap",
            "legend of zelda - the minish cap",
            "minish cap",
        ],
        display_name: "The Legend of Zelda: The Minish Cap",
        genre: "Aventura",
        developer: "Capcom / Flagship",
        publisher: "Nintendo",
        release_year: 2004,
        franchise: Some("The Legend of Zelda"),
    },
    CuratedMetaEntry {
        platforms: &["GBA"],
        keys: &["kingdom hearts - chain of memories", "chain of memories"],
        display_name: "Kingdom Hearts: Chain of Memories",
        genre: "Rol / RPG",
        developer: "Jupiter / Square Enix",
        publisher: "Square Enix",
        release_year: 2004,
        franchise: Some("Kingdom Hearts"),
    },
    CuratedMetaEntry {
        platforms: &["GBA"],
        keys: &[
            "kirby & the amazing mirror",
            "the amazing mirror",
            "amazing mirror",
            "kirby el laberinto de los espejos",
        ],
        display_name: "Kirby & The Amazing Mirror",
        genre: "Plataformas",
        developer: "HAL Laboratory / Flagship",
        publisher: "Nintendo",
        release_year: 2004,
        franchise: Some("Kirby"),
    },
    CuratedMetaEntry {
        platforms: &["GBA"],
        keys: &[
            "mario kart - super circuit",
            "super circuit",
            "mario kart super circuit",
        ],
        display_name: "Mario Kart: Super Circuit",
        genre: "Carreras",
        developer: "Intelligent Systems",
        publisher: "Nintendo",
        release_year: 2001,
        franchise: Some("Mario Kart"),
    },
    CuratedMetaEntry {
        platforms: &["GBA"],
        keys: &["castlevania - aria of sorrow", "aria of sorrow"],
        display_name: "Castlevania: Aria of Sorrow",
        genre: "Rol / RPG",
        developer: "Konami Computer Entertainment Tokyo",
        publisher: "Konami",
        release_year: 2003,
        franchise: Some("Castlevania"),
    },
    CuratedMetaEntry {
        platforms: &["GBA"],
        keys: &[
            "castlevania - harmony of dissonance",
            "harmony of dissonance",
        ],
        display_name: "Castlevania: Harmony of Dissonance",
        genre: "Rol / RPG",
        developer: "Konami Computer Entertainment Tokyo",
        publisher: "Konami",
        release_year: 2002,
        franchise: Some("Castlevania"),
    },
    CuratedMetaEntry {
        platforms: &["GBA"],
        keys: &["final fantasy tactics advance", "tactics advance"],
        display_name: "Final Fantasy Tactics Advance",
        genre: "Estrategia",
        developer: "Square Enix",
        publisher: "Square Enix / Nintendo",
        release_year: 2003,
        franchise: Some("Final Fantasy"),
    },
    CuratedMetaEntry {
        platforms: &["GBA"],
        keys: &[
            "fire emblem - the sacred stones",
            "the sacred stones",
            "sacred stones",
        ],
        display_name: "Fire Emblem: The Sacred Stones",
        genre: "Estrategia",
        developer: "Intelligent Systems",
        publisher: "Nintendo",
        release_year: 2004,
        franchise: Some("Fire Emblem"),
    },
    CuratedMetaEntry {
        platforms: &["GBA"],
        keys: &[
            "fire emblem - fuuin no tsurugi",
            "fuuin no tsurugi",
            "binding blade",
        ],
        display_name: "Fire Emblem: The Binding Blade",
        genre: "Estrategia",
        developer: "Intelligent Systems",
        publisher: "Nintendo",
        release_year: 2002,
        franchise: Some("Fire Emblem"),
    },
    CuratedMetaEntry {
        platforms: &["GBA"],
        keys: &["boktai - the sun is in your hand", "boktai"],
        display_name: "Boktai: The Sun Is in Your Hand",
        genre: "Aventura",
        developer: "Konami Computer Entertainment Japan",
        publisher: "Konami",
        release_year: 2003,
        franchise: Some("Boktai"),
    },
    CuratedMetaEntry {
        platforms: &["GBA"],
        keys: &["boktai 2 - solar boy django", "boktai 2"],
        display_name: "Boktai 2: Solar Boy Django",
        genre: "Aventura",
        developer: "Konami Computer Entertainment Japan",
        publisher: "Konami",
        release_year: 2004,
        franchise: Some("Boktai"),
    },
    CuratedMetaEntry {
        platforms: &["GBA"],
        keys: &["beyblade g-revolution", "beyblade g revolution"],
        display_name: "Beyblade G-Revolution",
        genre: "Acción / Lucha",
        developer: "SIMS",
        publisher: "Atari",
        release_year: 2004,
        franchise: Some("Beyblade"),
    },
    CuratedMetaEntry {
        platforms: &["GBA"],
        keys: &[
            "beyblade v-force - ultimate blader jam",
            "beyblade v-force",
            "beyblade v force",
        ],
        display_name: "Beyblade V-Force: Ultimate Blader Jam",
        genre: "Acción",
        developer: "Natsume",
        publisher: "Atari",
        release_year: 2003,
        franchise: Some("Beyblade"),
    },
    // --- SNES CLÁSICOS ---
    CuratedMetaEntry {
        platforms: &["SNES"],
        keys: &[
            "super metroid",
            "super metroid (europe)",
            "super metroid (usa)",
        ],
        display_name: "Super Metroid",
        genre: "Acción",
        developer: "Nintendo R&D1 / Intelligent Systems",
        publisher: "Nintendo",
        release_year: 1994,
        franchise: Some("Metroid"),
    },
    CuratedMetaEntry {
        platforms: &["SNES"],
        keys: &["chrono trigger"],
        display_name: "Chrono Trigger",
        genre: "Rol / RPG",
        developer: "SquareSoft",
        publisher: "SquareSoft",
        release_year: 1995,
        franchise: Some("Chrono"),
    },
    CuratedMetaEntry {
        platforms: &["SNES"],
        keys: &[
            "donkey kong country 2 - diddy's kong quest",
            "donkey kong country 2",
            "diddy's kong quest",
        ],
        display_name: "Donkey Kong Country 2: Diddy's Kong Quest",
        genre: "Plataformas",
        developer: "Rare Ltd.",
        publisher: "Nintendo",
        release_year: 1995,
        franchise: Some("Donkey Kong"),
    },
    CuratedMetaEntry {
        platforms: &["SNES"],
        keys: &[
            "donkey kong country 3 - dixie kong's double trouble!",
            "donkey kong country 3",
            "dixie kong's double trouble",
        ],
        display_name: "Donkey Kong Country 3: Dixie Kong's Double Trouble!",
        genre: "Plataformas",
        developer: "Rare Ltd.",
        publisher: "Nintendo",
        release_year: 1996,
        franchise: Some("Donkey Kong"),
    },
    CuratedMetaEntry {
        platforms: &["SNES"],
        keys: &["donkey kong country", "super donkey kong"],
        display_name: "Donkey Kong Country",
        genre: "Plataformas",
        developer: "Rare Ltd.",
        publisher: "Nintendo",
        release_year: 1994,
        franchise: Some("Donkey Kong"),
    },
    CuratedMetaEntry {
        platforms: &["SNES"],
        keys: &["earthbound", "mother 2"],
        display_name: "EarthBound",
        genre: "Rol / RPG",
        developer: "Ape / HAL Laboratory",
        publisher: "Nintendo",
        release_year: 1994,
        franchise: Some("Mother / EarthBound"),
    },
    CuratedMetaEntry {
        platforms: &["SNES"],
        keys: &["super mario world 2 - yoshi's island", "yoshi's island"],
        display_name: "Super Mario World 2: Yoshi's Island",
        genre: "Plataformas",
        developer: "Nintendo EAD",
        publisher: "Nintendo",
        release_year: 1995,
        franchise: Some("Mario"),
    },
    CuratedMetaEntry {
        platforms: &["SNES"],
        keys: &["super mario world"],
        display_name: "Super Mario World",
        genre: "Plataformas",
        developer: "Nintendo EAD",
        publisher: "Nintendo",
        release_year: 1990,
        franchise: Some("Mario"),
    },
    CuratedMetaEntry {
        platforms: &["SNES"],
        keys: &[
            "super mario rpg - legend of the seven stars",
            "super mario rpg",
            "legend of the seven stars",
        ],
        display_name: "Super Mario RPG: Legend of the Seven Stars",
        genre: "Rol / RPG",
        developer: "SquareSoft / Nintendo",
        publisher: "Nintendo",
        release_year: 1996,
        franchise: Some("Mario"),
    },
    CuratedMetaEntry {
        platforms: &["SNES"],
        keys: &[
            "legend of zelda, the - a link to the past",
            "a link to the past",
            "link to the past",
        ],
        display_name: "The Legend of Zelda: A Link to the Past",
        genre: "Aventura",
        developer: "Nintendo EAD",
        publisher: "Nintendo",
        release_year: 1991,
        franchise: Some("The Legend of Zelda"),
    },
    CuratedMetaEntry {
        platforms: &["SNES"],
        keys: &["secret of mana", "seiken densetsu 2"],
        display_name: "Secret of Mana",
        genre: "Rol / RPG",
        developer: "SquareSoft",
        publisher: "SquareSoft",
        release_year: 1993,
        franchise: Some("Mana"),
    },
    CuratedMetaEntry {
        platforms: &["SNES"],
        keys: &["secret of evermore"],
        display_name: "Secret of Evermore",
        genre: "Rol / RPG",
        developer: "SquareSoft",
        publisher: "SquareSoft",
        release_year: 1995,
        franchise: None,
    },
    CuratedMetaEntry {
        platforms: &["SNES"],
        keys: &["terranigma"],
        display_name: "Terranigma",
        genre: "Rol / RPG",
        developer: "Quintet",
        publisher: "Enix / Nintendo",
        release_year: 1995,
        franchise: None,
    },
    CuratedMetaEntry {
        platforms: &["SNES"],
        keys: &["illusion of time", "illusion of gaia"],
        display_name: "Illusion of Time",
        genre: "Rol / RPG",
        developer: "Quintet",
        publisher: "Enix / Nintendo",
        release_year: 1993,
        franchise: None,
    },
    CuratedMetaEntry {
        platforms: &["SNES"],
        keys: &["mega man x3", "megaman x3"],
        display_name: "Mega Man X3",
        genre: "Acción",
        developer: "Capcom",
        publisher: "Capcom",
        release_year: 1995,
        franchise: Some("Mega Man"),
    },
    CuratedMetaEntry {
        platforms: &["SNES"],
        keys: &["mega man x2", "megaman x2"],
        display_name: "Mega Man X2",
        genre: "Acción",
        developer: "Capcom",
        publisher: "Capcom",
        release_year: 1994,
        franchise: Some("Mega Man"),
    },
    CuratedMetaEntry {
        platforms: &["SNES"],
        keys: &["mega man x", "megaman x"],
        display_name: "Mega Man X",
        genre: "Acción",
        developer: "Capcom",
        publisher: "Capcom",
        release_year: 1993,
        franchise: Some("Mega Man"),
    },
    CuratedMetaEntry {
        platforms: &["SNES"],
        keys: &["castlevania - dracula x", "dracula x"],
        display_name: "Castlevania: Dracula X",
        genre: "Plataformas",
        developer: "Konami",
        publisher: "Konami",
        release_year: 1995,
        franchise: Some("Castlevania"),
    },
    CuratedMetaEntry {
        platforms: &["SNES"],
        keys: &[
            "turtles in time",
            "teenage mutant ninja turtles iv - turtles in time",
        ],
        display_name: "TMNT IV: Turtles in Time",
        genre: "Acción",
        developer: "Konami",
        publisher: "Konami",
        release_year: 1992,
        franchise: Some("TMNT"),
    },
    // --- PLAYSTATION 1 & 2 ---
    CuratedMetaEntry {
        platforms: &["PS1"],
        keys: &["metal gear solid", "mgs"],
        display_name: "Metal Gear Solid",
        genre: "Acción",
        developer: "Konami Computer Entertainment Japan",
        publisher: "Konami",
        release_year: 1998,
        franchise: Some("Metal Gear"),
    },
    CuratedMetaEntry {
        platforms: &["PS1"],
        keys: &[
            "castlevania - symphony of the night",
            "symphony of the night",
        ],
        display_name: "Castlevania: Symphony of the Night",
        genre: "Rol / RPG",
        developer: "Konami Computer Entertainment Tokyo",
        publisher: "Konami",
        release_year: 1997,
        franchise: Some("Castlevania"),
    },
    CuratedMetaEntry {
        platforms: &["PS1"],
        keys: &[
            "the legend of the dragoon",
            "legend of the dragoon",
            "legend of dragoon",
        ],
        display_name: "The Legend of Dragoon",
        genre: "Rol / RPG",
        developer: "Sony Computer Entertainment Japan",
        publisher: "Sony Computer Entertainment",
        release_year: 1999,
        franchise: Some("The Legend of Dragoon"),
    },
    CuratedMetaEntry {
        platforms: &["PS1"],
        keys: &["vagrant story"],
        display_name: "Vagrant Story",
        genre: "Rol / RPG",
        developer: "SquareSoft",
        publisher: "SquareSoft",
        release_year: 2000,
        franchise: None,
    },
    CuratedMetaEntry {
        platforms: &["PS1"],
        keys: &["xenogears"],
        display_name: "Xenogears",
        genre: "Rol / RPG",
        developer: "SquareSoft",
        publisher: "SquareSoft",
        release_year: 1998,
        franchise: Some("Xeno"),
    },
    CuratedMetaEntry {
        platforms: &["PS1"],
        keys: &["chrono cross"],
        display_name: "Chrono Cross",
        genre: "Rol / RPG",
        developer: "SquareSoft",
        publisher: "SquareSoft",
        release_year: 1999,
        franchise: Some("Chrono"),
    },
    CuratedMetaEntry {
        platforms: &["PS1"],
        keys: &["breath of fire iv", "breath of fire 4"],
        display_name: "Breath of Fire IV",
        genre: "Rol / RPG",
        developer: "Capcom",
        publisher: "Capcom",
        release_year: 2000,
        franchise: Some("Breath of Fire"),
    },
    CuratedMetaEntry {
        platforms: &["PS1"],
        keys: &["digimon world 2003", "digimon world 3"],
        display_name: "Digimon World 2003",
        genre: "Rol / RPG",
        developer: "Bandai",
        publisher: "Bandai",
        release_year: 2002,
        franchise: Some("Digimon"),
    },
    // --- PS2 ---
    CuratedMetaEntry {
        platforms: &["PS2"],
        keys: &["shadow of the colossus"],
        display_name: "Shadow of the Colossus",
        genre: "Acción / Aventura",
        developer: "Team Ico",
        publisher: "Sony Computer Entertainment",
        release_year: 2005,
        franchise: Some("Ico"),
    },
    CuratedMetaEntry {
        platforms: &["PS2"],
        keys: &["ico"],
        display_name: "Ico",
        genre: "Aventura / Puzle",
        developer: "Team Ico",
        publisher: "Sony Computer Entertainment",
        release_year: 2001,
        franchise: Some("Ico"),
    },
    CuratedMetaEntry {
        platforms: &["PS2"],
        keys: &["god of war ii", "god of war 2"],
        display_name: "God of War II",
        genre: "Acción / Hack and Slash",
        developer: "Santa Monica Studio",
        publisher: "Sony Computer Entertainment",
        release_year: 2007,
        franchise: Some("God of War"),
    },
    CuratedMetaEntry {
        platforms: &["PS2"],
        keys: &["god of war"],
        display_name: "God of War",
        genre: "Acción / Hack and Slash",
        developer: "Santa Monica Studio",
        publisher: "Sony Computer Entertainment",
        release_year: 2005,
        franchise: Some("God of War"),
    },
    CuratedMetaEntry {
        platforms: &["PS2"],
        keys: &[
            "grand theft auto - san andreas",
            "gta san andreas",
            "grand theft auto san andreas",
        ],
        display_name: "Grand Theft Auto: San Andreas",
        genre: "Acción / Sandbox",
        developer: "Rockstar North",
        publisher: "Rockstar Games",
        release_year: 2004,
        franchise: Some("Grand Theft Auto"),
    },
    CuratedMetaEntry {
        platforms: &["PS2"],
        keys: &["silent hill 2"],
        display_name: "Silent Hill 2",
        genre: "Terror / Supervivencia",
        developer: "Team Silent",
        publisher: "Konami",
        release_year: 2001,
        franchise: Some("Silent Hill"),
    },
    CuratedMetaEntry {
        platforms: &["PS2"],
        keys: &["metal gear solid 3 - snake eater", "metal gear solid 3"],
        display_name: "Metal Gear Solid 3: Snake Eater",
        genre: "Sigilo / Acción",
        developer: "Konami Computer Entertainment Japan",
        publisher: "Konami",
        release_year: 2004,
        franchise: Some("Metal Gear"),
    },
    CuratedMetaEntry {
        platforms: &["PS2"],
        keys: &["the king of fighters xi", "king of fighters xi", "kof xi"],
        display_name: "The King of Fighters XI",
        genre: "Lucha",
        developer: "SNK Playmore",
        publisher: "SNK Playmore",
        release_year: 2005,
        franchise: Some("The King of Fighters"),
    },
    // --- PSP ---
    CuratedMetaEntry {
        platforms: &["PSP"],
        keys: &["patapon 3"],
        display_name: "Patapon 3",
        genre: "Ritmo / Música",
        developer: "Pyramid / Japan Studio",
        publisher: "Sony Computer Entertainment",
        release_year: 2011,
        franchise: Some("Patapon"),
    },
    CuratedMetaEntry {
        platforms: &["PSP"],
        keys: &["patapon 2"],
        display_name: "Patapon 2",
        genre: "Ritmo / Música",
        developer: "Pyramid / Japan Studio",
        publisher: "Sony Computer Entertainment",
        release_year: 2008,
        franchise: Some("Patapon"),
    },
    CuratedMetaEntry {
        platforms: &["PSP"],
        keys: &["patapon"],
        display_name: "Patapon",
        genre: "Ritmo / Música",
        developer: "Pyramid / Japan Studio",
        publisher: "Sony Computer Entertainment",
        release_year: 2007,
        franchise: Some("Patapon"),
    },
    CuratedMetaEntry {
        platforms: &["PSP"],
        keys: &["locoroco 2"],
        display_name: "LocoRoco 2",
        genre: "Plataformas",
        developer: "Japan Studio",
        publisher: "Sony Computer Entertainment",
        release_year: 2008,
        franchise: Some("LocoRoco"),
    },
    CuratedMetaEntry {
        platforms: &["PSP"],
        keys: &["locoroco"],
        display_name: "LocoRoco",
        genre: "Plataformas",
        developer: "Japan Studio",
        publisher: "Sony Computer Entertainment",
        release_year: 2006,
        franchise: Some("LocoRoco"),
    },
    CuratedMetaEntry {
        platforms: &["PSP"],
        keys: &[
            "dissidia 012 - duodecim final fantasy",
            "dissidia 012",
            "duodecim",
        ],
        display_name: "Dissidia 012: Duodecim Final Fantasy",
        genre: "Lucha",
        developer: "Square Enix",
        publisher: "Square Enix",
        release_year: 2011,
        franchise: Some("Final Fantasy"),
    },
    CuratedMetaEntry {
        platforms: &["PSP"],
        keys: &["wizorb"],
        display_name: "Wizorb",
        genre: "Puzle / Breakout",
        developer: "Tribute Games",
        publisher: "Tribute Games",
        release_year: 2011,
        franchise: None,
    },
    // --- PS3 ---
    CuratedMetaEntry {
        platforms: &["PS3"],
        keys: &["dragon's crown", "dragons crown"],
        display_name: "Dragon's Crown",
        genre: "Acción / Rol",
        developer: "Vanillaware",
        publisher: "Atlus",
        release_year: 2013,
        franchise: None,
    },
    CuratedMetaEntry {
        platforms: &["PS3"],
        keys: &["god of war collection"],
        display_name: "God of War Collection",
        genre: "Acción / Hack and Slash",
        developer: "Bluepoint Games",
        publisher: "Sony Computer Entertainment",
        release_year: 2009,
        franchise: Some("God of War"),
    },
    // --- GAMECUBE ---
    CuratedMetaEntry {
        platforms: &["GAMECUBE", "GameCube", "NGC"],
        keys: &[
            "mario kart - double dash!!",
            "mario kart double dash",
            "mario kart - double dash",
        ],
        display_name: "Mario Kart: Double Dash!!",
        genre: "Carreras",
        developer: "Nintendo EAD",
        publisher: "Nintendo",
        release_year: 2003,
        franchise: Some("Mario Kart"),
    },
    CuratedMetaEntry {
        platforms: &["GAMECUBE", "GameCube", "NGC"],
        keys: &[
            "the legend of zelda - the wind waker",
            "legend of zelda, the - the wind waker",
            "wind waker",
        ],
        display_name: "The Legend of Zelda: The Wind Waker",
        genre: "Aventura / Acción",
        developer: "Nintendo EAD",
        publisher: "Nintendo",
        release_year: 2002,
        franchise: Some("The Legend of Zelda"),
    },
    CuratedMetaEntry {
        platforms: &["GAMECUBE", "GameCube", "NGC"],
        keys: &["metroid prime"],
        display_name: "Metroid Prime",
        genre: "Acción / Aventura",
        developer: "Retro Studios",
        publisher: "Nintendo",
        release_year: 2002,
        franchise: Some("Metroid"),
    },
    CuratedMetaEntry {
        platforms: &["GAMECUBE", "GameCube", "NGC"],
        keys: &["super smash bros. melee", "smash bros melee", "melee"],
        display_name: "Super Smash Bros. Melee",
        genre: "Lucha",
        developer: "HAL Laboratory",
        publisher: "Nintendo",
        release_year: 2001,
        franchise: Some("Super Smash Bros."),
    },
    CuratedMetaEntry {
        platforms: &["GAMECUBE", "GameCube", "NGC"],
        keys: &["mario party 7"],
        display_name: "Mario Party 7",
        genre: "Party / Minijuegos",
        developer: "Hudson Soft",
        publisher: "Nintendo",
        release_year: 2005,
        franchise: Some("Mario Party"),
    },
    // --- MEGA DRIVE & SMS ---
    CuratedMetaEntry {
        platforms: &["MEGA_DRIVE"],
        keys: &["sonic the hedgehog 3", "sonic 3"],
        display_name: "Sonic The Hedgehog 3",
        genre: "Plataformas",
        developer: "Sonic Team",
        publisher: "Sega",
        release_year: 1994,
        franchise: Some("Sonic The Hedgehog"),
    },
    CuratedMetaEntry {
        platforms: &["MEGA_DRIVE"],
        keys: &["sonic the hedgehog 2", "sonic 2"],
        display_name: "Sonic The Hedgehog 2",
        genre: "Plataformas",
        developer: "Sega Technical Institute",
        publisher: "Sega",
        release_year: 1992,
        franchise: Some("Sonic The Hedgehog"),
    },
    CuratedMetaEntry {
        platforms: &["MEGA_DRIVE"],
        keys: &["sonic the hedgehog", "sonic 1"],
        display_name: "Sonic The Hedgehog",
        genre: "Plataformas",
        developer: "Sonic Team",
        publisher: "Sega",
        release_year: 1991,
        franchise: Some("Sonic The Hedgehog"),
    },
    CuratedMetaEntry {
        platforms: &["MEGA_DRIVE"],
        keys: &["gunstar heroes"],
        display_name: "Gunstar Heroes",
        genre: "Acción",
        developer: "Treasure",
        publisher: "Sega",
        release_year: 1993,
        franchise: None,
    },
    CuratedMetaEntry {
        platforms: &["SMS"],
        keys: &["alex kidd in miracle world"],
        display_name: "Alex Kidd in Miracle World",
        genre: "Plataformas",
        developer: "Sega",
        publisher: "Sega",
        release_year: 1986,
        franchise: Some("Alex Kidd"),
    },
    CuratedMetaEntry {
        platforms: &["SMS"],
        keys: &["alex kidd in shinobi world"],
        display_name: "Alex Kidd in Shinobi World",
        genre: "Plataformas",
        developer: "Sega",
        publisher: "Sega",
        release_year: 1990,
        franchise: Some("Alex Kidd"),
    },
    CuratedMetaEntry {
        platforms: &["SMS"],
        keys: &["golden axe warrior"],
        display_name: "Golden Axe Warrior",
        genre: "Aventura",
        developer: "Sega",
        publisher: "Sega",
        release_year: 1991,
        franchise: Some("Golden Axe"),
    },
    CuratedMetaEntry {
        platforms: &["SMS"],
        keys: &["line of fire"],
        display_name: "Line of Fire",
        genre: "Shooter / Disparos",
        developer: "Sega",
        publisher: "Sega",
        release_year: 1991,
        franchise: None,
    },
    // --- NINTENDO DS CLÁSICOS & SAGAS POPULARES ---
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["pokemon - edicion blanca 2", "pokemon blanca 2", "pokemon blanco 2", "white 2"],
        display_name: "Pokémon Edición Blanca 2",
        genre: "Rol / RPG",
        developer: "Game Freak",
        publisher: "Nintendo",
        release_year: 2012,
        franchise: Some("Pokemon"),
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["pokemon - edicion negra 2", "pokemon negra 2", "pokemon negro 2", "black 2"],
        display_name: "Pokémon Edición Negra 2",
        genre: "Rol / RPG",
        developer: "Game Freak",
        publisher: "Nintendo",
        release_year: 2012,
        franchise: Some("Pokemon"),
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["pokemon - edicion blanca", "pokemon blanca", "pokemon blanco", "white version"],
        display_name: "Pokémon Edición Blanca",
        genre: "Rol / RPG",
        developer: "Game Freak",
        publisher: "Nintendo",
        release_year: 2010,
        franchise: Some("Pokemon"),
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["pokemon - edicion negra", "pokemon negra", "pokemon negro", "black version"],
        display_name: "Pokémon Edición Negra",
        genre: "Rol / RPG",
        developer: "Game Freak",
        publisher: "Nintendo",
        release_year: 2010,
        franchise: Some("Pokemon"),
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["pokemon - edicion diamante", "pokemon diamante", "diamond version"],
        display_name: "Pokémon Edición Diamante",
        genre: "Rol / RPG",
        developer: "Game Freak",
        publisher: "Nintendo",
        release_year: 2006,
        franchise: Some("Pokemon"),
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["pokemon - edicion perla", "pokemon perla", "pearl version"],
        display_name: "Pokémon Edición Perla",
        genre: "Rol / RPG",
        developer: "Game Freak",
        publisher: "Nintendo",
        release_year: 2006,
        franchise: Some("Pokemon"),
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["pokemon - edicion platino", "pokemon platino", "platinum version"],
        display_name: "Pokémon Edición Platino",
        genre: "Rol / RPG",
        developer: "Game Freak",
        publisher: "Nintendo",
        release_year: 2008,
        franchise: Some("Pokemon"),
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["pokemon - edicion oro heartgold", "pokemon heartgold", "oro heartgold"],
        display_name: "Pokémon Edición Oro HeartGold",
        genre: "Rol / RPG",
        developer: "Game Freak",
        publisher: "Nintendo",
        release_year: 2009,
        franchise: Some("Pokemon"),
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["pokemon - edicion plata soulsilver", "pokemon soulsilver", "plata soulsilver"],
        display_name: "Pokémon Edición Plata SoulSilver",
        genre: "Rol / RPG",
        developer: "Game Freak",
        publisher: "Nintendo",
        release_year: 2009,
        franchise: Some("Pokemon"),
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["pokemon conquest"],
        display_name: "Pokémon Conquest",
        genre: "Estrategia / Rol",
        developer: "Tecmo Koei",
        publisher: "Nintendo",
        release_year: 2012,
        franchise: Some("Pokemon"),
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["pokemon ranger - shadows of almia", "sombras de almia"],
        display_name: "Pokémon Ranger: Sombras de Almia",
        genre: "Aventura / Rol",
        developer: "Creatures Inc.",
        publisher: "Nintendo",
        release_year: 2008,
        franchise: Some("Pokemon"),
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["pokemon ranger"],
        display_name: "Pokémon Ranger",
        genre: "Aventura / Rol",
        developer: "Creatures Inc.",
        publisher: "Nintendo",
        release_year: 2006,
        franchise: Some("Pokemon"),
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["equipo de rescate azul", "blue rescue team"],
        display_name: "Pokémon Mundo Misterioso: Equipo de Rescate Azul",
        genre: "Roguelike / Rol",
        developer: "Chunsoft",
        publisher: "Nintendo",
        release_year: 2005,
        franchise: Some("Pokemon"),
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["exploradores del tiempo", "explorers of time"],
        display_name: "Pokémon Mundo Misterioso: Exploradores del Tiempo",
        genre: "Roguelike / Rol",
        developer: "Chunsoft",
        publisher: "Nintendo",
        release_year: 2007,
        franchise: Some("Pokemon"),
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["exploradores de la oscuridad", "explorers of darkness"],
        display_name: "Pokémon Mundo Misterioso: Exploradores de la Oscuridad",
        genre: "Roguelike / Rol",
        developer: "Chunsoft",
        publisher: "Nintendo",
        release_year: 2007,
        franchise: Some("Pokemon"),
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["explotadores del cielo", "exploradores del cielo", "explorers of sky"],
        display_name: "Pokémon Mundo Misterioso: Exploradores del Cielo",
        genre: "Roguelike / Rol",
        developer: "Chunsoft",
        publisher: "Nintendo",
        release_year: 2009,
        franchise: Some("Pokemon"),
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["dragon quest iv", "capitulo de los elegidos", "chapters of the chosen"],
        display_name: "Dragon Quest IV: Capítulos de los Elegidos",
        genre: "Rol / RPG",
        developer: "ArtePiazza",
        publisher: "Square Enix",
        release_year: 2007,
        franchise: Some("Dragon Quest"),
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["dragon quest v", "hand of the heavenly bride", "prometida celestial"],
        display_name: "Dragon Quest V: La Prometida Celestial",
        genre: "Rol / RPG",
        developer: "ArtePiazza",
        publisher: "Square Enix",
        release_year: 2008,
        franchise: Some("Dragon Quest"),
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["dragon quest vi", "los reinos oniricos", "reinos oniricos", "realms of revelation"],
        display_name: "Dragon Quest VI: Los Reinos Oníricos",
        genre: "Rol / RPG",
        developer: "ArtePiazza",
        publisher: "Square Enix",
        release_year: 2010,
        franchise: Some("Dragon Quest"),
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["dragon quest ix", "sentinels of the starry skies", "centinelas del firmamento"],
        display_name: "Dragon Quest IX: Centinelas del Firmamento",
        genre: "Rol / RPG",
        developer: "Level-5",
        publisher: "Square Enix",
        release_year: 2009,
        franchise: Some("Dragon Quest"),
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["dragon quest monsters - joker 2", "monsters joker 2"],
        display_name: "Dragon Quest Monsters: Joker 2",
        genre: "Rol / RPG",
        developer: "TOSE",
        publisher: "Square Enix",
        release_year: 2010,
        franchise: Some("Dragon Quest"),
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["dragon quest monsters - joker", "monsters joker"],
        display_name: "Dragon Quest Monsters: Joker",
        genre: "Rol / RPG",
        developer: "TOSE",
        publisher: "Square Enix",
        release_year: 2006,
        franchise: Some("Dragon Quest"),
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["villa misteriosa", "curious village"],
        display_name: "El Profesor Layton y la Villa Misteriosa",
        genre: "Puzle / Aventura",
        developer: "Level-5",
        publisher: "Nintendo",
        release_year: 2007,
        franchise: Some("Profesor Layton"),
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["caja de pandora", "diabolical box", "pandora's box"],
        display_name: "El Profesor Layton y la Caja de Pandora",
        genre: "Puzle / Aventura",
        developer: "Level-5",
        publisher: "Nintendo",
        release_year: 2007,
        franchise: Some("Profesor Layton"),
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["futuro perdido", "unwound future", "lost future"],
        display_name: "El Profesor Layton y el Futuro Perdido",
        genre: "Puzle / Aventura",
        developer: "Level-5",
        publisher: "Nintendo",
        release_year: 2008,
        franchise: Some("Profesor Layton"),
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["llamada del espectro", "last specter", "spectre's call"],
        display_name: "El Profesor Layton y la Llamada del Espectro",
        genre: "Puzle / Aventura",
        developer: "Level-5",
        publisher: "Nintendo",
        release_year: 2009,
        franchise: Some("Profesor Layton"),
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["bowser's inside story", "viaje al centro de bowser"],
        display_name: "Mario & Luigi: Viaje al Centro de Bowser",
        genre: "Rol / RPG",
        developer: "AlphaDream",
        publisher: "Nintendo",
        release_year: 2009,
        franchise: Some("Mario"),
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["companeros en el tiempo", "partners in time"],
        display_name: "Mario & Luigi: Compañeros en el Tiempo",
        genre: "Rol / RPG",
        developer: "AlphaDream",
        publisher: "Nintendo",
        release_year: 2005,
        franchise: Some("Mario"),
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["justice for all"],
        display_name: "Phoenix Wright: Ace Attorney - Justice For All",
        genre: "Novela Visual / Aventura",
        developer: "Capcom",
        publisher: "Capcom",
        release_year: 2006,
        franchise: Some("Ace Attorney"),
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["trials and tribulations"],
        display_name: "Phoenix Wright: Ace Attorney - Trials and Tribulations",
        genre: "Novela Visual / Aventura",
        developer: "Capcom",
        publisher: "Capcom",
        release_year: 2007,
        franchise: Some("Ace Attorney"),
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["phoenix wright - ace attorney", "phoenix wright ace attorney"],
        display_name: "Phoenix Wright: Ace Attorney",
        genre: "Novela Visual / Aventura",
        developer: "Capcom",
        publisher: "Capcom",
        release_year: 2005,
        franchise: Some("Ace Attorney"),
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["apollo justice"],
        display_name: "Apollo Justice: Ace Attorney",
        genre: "Novela Visual / Aventura",
        developer: "Capcom",
        publisher: "Capcom",
        release_year: 2007,
        franchise: Some("Ace Attorney"),
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["miles edgeworth", "ace attorney investigations"],
        display_name: "Ace Attorney Investigations: Miles Edgeworth",
        genre: "Novela Visual / Aventura",
        developer: "Capcom",
        publisher: "Capcom",
        release_year: 2009,
        franchise: Some("Ace Attorney"),
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["final fantasy iii", "final fantasy 3"],
        display_name: "Final Fantasy III",
        genre: "Rol / RPG",
        developer: "Matrix Software",
        publisher: "Square Enix",
        release_year: 2006,
        franchise: Some("Final Fantasy"),
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["final fantasy iv", "final fantasy 4"],
        display_name: "Final Fantasy IV",
        genre: "Rol / RPG",
        developer: "Matrix Software",
        publisher: "Square Enix",
        release_year: 2007,
        franchise: Some("Final Fantasy"),
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["tactics a2", "grimoire of the rift"],
        display_name: "Final Fantasy Tactics A2: Grimoire of the Rift",
        genre: "Estrategia / Rol",
        developer: "Square Enix",
        publisher: "Square Enix",
        release_year: 2007,
        franchise: Some("Final Fantasy"),
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["revenant wings"],
        display_name: "Final Fantasy XII: Revenant Wings",
        genre: "Estrategia / Rol",
        developer: "Think & Feel",
        publisher: "Square Enix",
        release_year: 2007,
        franchise: Some("Final Fantasy"),
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["four heroes of light", "4 heroes of light"],
        display_name: "Final Fantasy: The 4 Heroes of Light",
        genre: "Rol / RPG",
        developer: "Matrix Software",
        publisher: "Square Enix",
        release_year: 2009,
        franchise: Some("Final Fantasy"),
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["chocobo tales"],
        display_name: "Final Fantasy Fables: Chocobo Tales",
        genre: "Aventura / Puzle",
        developer: "h.a.n.d.",
        publisher: "Square Enix",
        release_year: 2006,
        franchise: Some("Final Fantasy"),
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["the world ends with you", "world ends with you"],
        display_name: "The World Ends With You",
        genre: "Acción / RPG",
        developer: "Jupiter / Square Enix",
        publisher: "Square Enix",
        release_year: 2007,
        franchise: None,
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["chrono trigger"],
        display_name: "Chrono Trigger",
        genre: "Rol / RPG",
        developer: "TOSE",
        publisher: "Square Enix",
        release_year: 2008,
        franchise: Some("Chrono"),
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["children of mana"],
        display_name: "Children of Mana",
        genre: "Acción / RPG",
        developer: "Nex Entertainment",
        publisher: "Square Enix",
        release_year: 2006,
        franchise: Some("Mana"),
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["dawn of sorrow"],
        display_name: "Castlevania: Dawn of Sorrow",
        genre: "Metroidvania / Acción",
        developer: "Konami",
        publisher: "Konami",
        release_year: 2005,
        franchise: Some("Castlevania"),
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["portrait of ruin"],
        display_name: "Castlevania: Portrait of Ruin",
        genre: "Metroidvania / Acción",
        developer: "Konami",
        publisher: "Konami",
        release_year: 2006,
        franchise: Some("Castlevania"),
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["order of ecclesia"],
        display_name: "Castlevania: Order of Ecclesia",
        genre: "Metroidvania / Acción",
        developer: "Konami",
        publisher: "Konami",
        release_year: 2008,
        franchise: Some("Castlevania"),
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["kirby - mouse attack", "mouse attack", "squeak squad"],
        display_name: "Kirby: ¡Roedores al Ataque!",
        genre: "Plataformas",
        developer: "Flagship / HAL Laboratory",
        publisher: "Nintendo",
        release_year: 2006,
        franchise: Some("Kirby"),
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["canvas curse", "power paintbrush"],
        display_name: "Kirby: El Pincel del Poder",
        genre: "Plataformas / Puzle",
        developer: "HAL Laboratory",
        publisher: "Nintendo",
        release_year: 2005,
        franchise: Some("Kirby"),
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["super star ultra"],
        display_name: "Kirby Super Star Ultra",
        genre: "Plataformas",
        developer: "HAL Laboratory",
        publisher: "Nintendo",
        release_year: 2008,
        franchise: Some("Kirby"),
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["mass attack"],
        display_name: "Kirby Mass Attack",
        genre: "Plataformas / Puzle",
        developer: "HAL Laboratory",
        publisher: "Nintendo",
        release_year: 2011,
        franchise: Some("Kirby"),
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["oscuro amanecer", "dark dawn"],
        display_name: "Golden Sun: Oscuro Amanecer",
        genre: "Rol / RPG",
        developer: "Camelot",
        publisher: "Nintendo",
        release_year: 2010,
        franchise: Some("Golden Sun"),
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["shadow dragon"],
        display_name: "Fire Emblem: Shadow Dragon",
        genre: "Estrategia / Rol",
        developer: "Intelligent Systems",
        publisher: "Nintendo",
        release_year: 2008,
        franchise: Some("Fire Emblem"),
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["radiant historia"],
        display_name: "Radiant Historia",
        genre: "Rol / RPG",
        developer: "Atlus",
        publisher: "Atlus",
        release_year: 2010,
        franchise: None,
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["devil survivor 2"],
        display_name: "Shin Megami Tensei: Devil Survivor 2",
        genre: "Rol / Estrategia",
        developer: "Career Soft / Atlus",
        publisher: "Atlus",
        release_year: 2011,
        franchise: Some("Megami Tensei"),
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["advance wars - dual strike", "dual strike"],
        display_name: "Advance Wars: Dual Strike",
        genre: "Estrategia por Turnos",
        developer: "Intelligent Systems",
        publisher: "Nintendo",
        release_year: 2005,
        franchise: Some("Advance Wars"),
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["atelier annie"],
        display_name: "Atelier Annie: Alchemists of Sera Island",
        genre: "Rol / Simulación",
        developer: "Gust Co. Ltd.",
        publisher: "NIS America",
        release_year: 2009,
        franchise: Some("Atelier"),
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["avalon code"],
        display_name: "Avalon Code",
        genre: "Acción / RPG",
        developer: "Matrix Software",
        publisher: "Marvelous",
        release_year: 2008,
        franchise: None,
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["bakushow"],
        display_name: "Bakushow: Challenge Your Friends!",
        genre: "Puzle / Fiesta",
        developer: "BPlus",
        publisher: "Mindscape",
        release_year: 2008,
        franchise: None,
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["awakened shadow"],
        display_name: "Blue Dragon: Awakened Shadow",
        genre: "Rol / RPG",
        developer: "Mistwalker / tri-Crescendo",
        publisher: "D3Publisher",
        release_year: 2009,
        franchise: Some("Blue Dragon"),
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["blue dragon plus"],
        display_name: "Blue Dragon Plus",
        genre: "Estrategia / Rol",
        developer: "Mistwalker / Brownie Brown",
        publisher: "AQ Interactive",
        release_year: 2008,
        franchise: Some("Blue Dragon"),
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["contact"],
        display_name: "Contact",
        genre: "Rol / RPG",
        developer: "Grasshopper Manufacture",
        publisher: "Marvelous",
        release_year: 2006,
        franchise: None,
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["digimon world - dawn", "world dawn"],
        display_name: "Digimon World Dawn",
        genre: "Rol / RPG",
        developer: "BEC",
        publisher: "Bandai Namco",
        release_year: 2007,
        franchise: Some("Digimon"),
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["digimon world - dusk", "world dusk"],
        display_name: "Digimon World Dusk",
        genre: "Rol / RPG",
        developer: "BEC",
        publisher: "Bandai Namco",
        release_year: 2007,
        franchise: Some("Digimon"),
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["digimon world ds"],
        display_name: "Digimon World DS",
        genre: "Rol / RPG",
        developer: "BEC",
        publisher: "Bandai Namco",
        release_year: 2006,
        franchise: Some("Digimon"),
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["attack of the saiyans"],
        display_name: "Dragon Ball Z: Attack of the Saiyans",
        genre: "Rol / RPG",
        developer: "Monolith Soft",
        publisher: "Bandai Namco",
        release_year: 2009,
        franchise: Some("Dragon Ball"),
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["goku densetsu", "harukanaru densetsu"],
        display_name: "Dragon Ball Z: Harukanaru Densetsu",
        genre: "Rol / Cartas",
        developer: "BEC",
        publisher: "Bandai Namco",
        release_year: 2007,
        franchise: Some("Dragon Ball"),
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["eledees"],
        display_name: "Eledees: The Adventures of Kai and Zero",
        genre: "Aventura / Puzle",
        developer: "Konami",
        publisher: "Konami",
        release_year: 2008,
        franchise: None,
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["etrian odyssey ii", "etrian odyssey 2", "heroes of lagaard"],
        display_name: "Etrian Odyssey II: Heroes of Lagaard",
        genre: "Dungeon Crawler / RPG",
        developer: "Atlus",
        publisher: "Atlus",
        release_year: 2008,
        franchise: Some("Etrian Odyssey"),
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["etrian odyssey"],
        display_name: "Etrian Odyssey",
        genre: "Dungeon Crawler / RPG",
        developer: "Atlus",
        publisher: "Atlus",
        release_year: 2007,
        franchise: Some("Etrian Odyssey"),
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["jump! ultimate stars", "jump ultimate stars"],
        display_name: "Jump! Ultimate Stars",
        genre: "Lucha / Acción",
        developer: "Ganbarion",
        publisher: "Nintendo",
        release_year: 2006,
        franchise: None,
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["lock's quest", "locks quest"],
        display_name: "Lock's Quest",
        genre: "Estrategia / Tower Defense",
        developer: "5th Cell",
        publisher: "THQ",
        release_year: 2008,
        franchise: None,
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["lunar knights"],
        display_name: "Lunar Knights",
        genre: "Acción / RPG",
        developer: "Kojima Productions",
        publisher: "Konami",
        release_year: 2006,
        franchise: Some("Boktai"),
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["clash of heroes", "might & magic"],
        display_name: "Might & Magic: Clash of Heroes",
        genre: "Puzle / RPG",
        developer: "Capybara Games",
        publisher: "Ubisoft",
        release_year: 2009,
        franchise: Some("Might & Magic"),
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["nostalgia"],
        display_name: "Nostalgia",
        genre: "Rol / RPG",
        developer: "Matrix Software",
        publisher: "Ignition Entertainment",
        release_year: 2008,
        franchise: None,
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["rhythm paradise", "rhythm heaven"],
        display_name: "Rhythm Paradise",
        genre: "Ritmo / Musical",
        developer: "Nintendo SPD",
        publisher: "Nintendo",
        release_year: 2008,
        franchise: Some("Rhythm Heaven"),
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["soma bringer"],
        display_name: "Soma Bringer",
        genre: "Acción / RPG",
        developer: "Monolith Soft",
        publisher: "Nintendo",
        release_year: 2008,
        franchise: None,
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["endless frontier", "super robot taisen og saga"],
        display_name: "Super Robot Taisen OG Saga: Endless Frontier",
        genre: "Rol / RPG",
        developer: "Monolith Soft",
        publisher: "Banpresto",
        release_year: 2008,
        franchise: Some("Super Robot Wars"),
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["super scribblenauts"],
        display_name: "Super Scribblenauts",
        genre: "Puzle / Sandbox",
        developer: "5th Cell",
        publisher: "Warner Bros.",
        release_year: 2010,
        franchise: Some("Scribblenauts"),
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["tao's adventure", "taos adventure"],
        display_name: "Tao's Adventure: Curse of the Demon Seal",
        genre: "Rol / RPG",
        developer: "Konami",
        publisher: "Konami",
        release_year: 2005,
        franchise: None,
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["time hollow"],
        display_name: "Time Hollow",
        genre: "Aventura Gráfica",
        developer: "Konami",
        publisher: "Konami",
        release_year: 2008,
        franchise: None,
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["trauma center"],
        display_name: "Trauma Center: Under the Knife",
        genre: "Simulación / Aventura",
        developer: "Atlus",
        publisher: "Atlus",
        release_year: 2005,
        franchise: Some("Trauma Center"),
    },
    // --- GBA, SNES, PSP JUEGOS CURADOS Y TRADUCCIONES ---
    CuratedMetaEntry {
        platforms: &["GBA"],
        keys: &[
            "dragon ball - advanced adventure",
            "dragon ball advanced adventure",
            "advanced adventure",
        ],
        display_name: "Dragon Ball: Advanced Adventure",
        genre: "Plataformas / Acción",
        developer: "Dimps",
        publisher: "Atari / Banpresto",
        release_year: 2004,
        franchise: Some("Dragon Ball"),
    },
    CuratedMetaEntry {
        platforms: &["GBA"],
        keys: &[
            "gekido advance - kintaro's revenge",
            "gekido advance",
            "kintaro's revenge",
            "gekido advance kintaros revenge",
        ],
        display_name: "Gekido Advance: Kintaro's Revenge",
        genre: "Beat 'em up / Acción",
        developer: "Naps Team",
        publisher: "Zoo Digital Publishing",
        release_year: 2002,
        franchise: Some("Gekido"),
    },
    CuratedMetaEntry {
        platforms: &["GBA"],
        keys: &[
            "medabots ax - metabee version",
            "medabots ax metabee",
            "medabots ax - metabee",
        ],
        display_name: "Medabots AX: Metabee Version",
        genre: "Lucha / RPG",
        developer: "Natsume",
        publisher: "Natsume",
        release_year: 2002,
        franchise: Some("Medabots"),
    },
    CuratedMetaEntry {
        platforms: &["GBA"],
        keys: &[
            "medabots ax - rokusho version",
            "medabots ax rokusho",
            "medabots ax - rokusho",
        ],
        display_name: "Medabots AX: Rokusho Version",
        genre: "Lucha / RPG",
        developer: "Natsume",
        publisher: "Natsume",
        release_year: 2002,
        franchise: Some("Medabots"),
    },
    CuratedMetaEntry {
        platforms: &["GBA"],
        keys: &[
            "mother 1+2",
            "mother 1 2",
            "mother 1 + 2",
            "earthbound 1+2",
        ],
        display_name: "Mother 1+2",
        genre: "Rol / RPG",
        developer: "Ape Inc. / HAL Laboratory",
        publisher: "Nintendo",
        release_year: 2003,
        franchise: Some("EarthBound / Mother"),
    },
    CuratedMetaEntry {
        platforms: &["GBA"],
        keys: &[
            "mother 3",
            "earthbound 2",
            "earthbound 3",
        ],
        display_name: "Mother 3",
        genre: "Rol / RPG",
        developer: "Brownie Brown / HAL Laboratory",
        publisher: "Nintendo",
        release_year: 2006,
        franchise: Some("EarthBound / Mother"),
    },
    CuratedMetaEntry {
        platforms: &["GBA", "NDS"],
        keys: &[
            "scurge - hive",
            "scurge hive",
            "scurge",
        ],
        display_name: "Scurge: Hive",
        genre: "Acción y Aventura / Metroidvania",
        developer: "Orbital Media",
        publisher: "SouthPeak Games",
        release_year: 2006,
        franchise: None,
    },
    CuratedMetaEntry {
        platforms: &["GBA"],
        keys: &[
            "summon night - swordcraft story",
            "summon night swordcraft story",
            "swordcraft story",
        ],
        display_name: "Summon Night: Swordcraft Story",
        genre: "Acción RPG",
        developer: "Flight-Plan",
        publisher: "Atlus / Banpresto",
        release_year: 2003,
        franchise: Some("Summon Night"),
    },
    CuratedMetaEntry {
        platforms: &["GBA"],
        keys: &[
            "warioware, inc. - minigame mania",
            "warioware inc minigame mania",
            "warioware inc",
            "warioware, inc.",
            "minigame mania",
        ],
        display_name: "WarioWare, Inc.: Minigame Mania",
        genre: "Minijuegos / Arcade",
        developer: "Nintendo R&D1",
        publisher: "Nintendo",
        release_year: 2003,
        franchise: Some("WarioWare"),
    },
    CuratedMetaEntry {
        platforms: &["GBA", "PSP"],
        keys: &[
            "yggdra union - we'll never fight alone",
            "yggdra union",
            "yggdra union well never fight alone",
        ],
        display_name: "Yggdra Union: We'll Never Fight Alone",
        genre: "Estrategia / RPG Táctico",
        developer: "Sting Entertainment",
        publisher: "Atlus",
        release_year: 2006,
        franchise: Some("Dept. Heaven"),
    },
    CuratedMetaEntry {
        platforms: &["PSP"],
        keys: &[
            "fat princess - fistful of cake",
            "fat princess fistful of cake",
            "fat princess",
        ],
        display_name: "Fat Princess: Fistful of Cake",
        genre: "Estrategia / Acción",
        developer: "SuperVillain Studios",
        publisher: "Sony Computer Entertainment",
        release_year: 2010,
        franchise: Some("Fat Princess"),
    },
    CuratedMetaEntry {
        platforms: &["SNES", "MEGA_DRIVE"],
        keys: &[
            "aero the acro-bat 2",
            "aero the acrobat 2",
        ],
        display_name: "Aero the Acro-Bat 2",
        genre: "Plataformas",
        developer: "Iguana Entertainment",
        publisher: "Sunsoft",
        release_year: 1994,
        franchise: Some("Aero the Acro-Bat"),
    },
];

fn normalize_for_match(s: &str) -> String {
    s.to_lowercase()
        .replace(['é', 'è', 'ê', 'ë'], "e")
        .replace(['á', 'à', 'â', 'ä'], "a")
        .replace(['í', 'ì', 'î', 'ï'], "i")
        .replace(['ó', 'ò', 'ô', 'ö'], "o")
        .replace(['ú', 'ù', 'û', 'ü'], "u")
        .replace('ñ', "n")
        .chars()
        .map(|c| if c.is_alphanumeric() { c } else { ' ' })
        .collect::<String>()
        .split_whitespace()
        .collect::<Vec<_>>()
        .join(" ")
}

pub fn find_curated_catalog_metadata(query: &str, platform: &str) -> Option<GameMetadata> {
    let q_clean = query
        .split(" (")
        .next()
        .unwrap_or(query)
        .split(" [")
        .next()
        .unwrap_or(query)
        .trim();
    let q_norm = normalize_for_match(q_clean);

    for entry in CURATED_CATALOG {
        if !entry
            .platforms
            .iter()
            .any(|&p| p.eq_ignore_ascii_case(platform))
        {
            continue;
        }

        for key in entry.keys {
            let k_norm = normalize_for_match(key);
            if q_norm == k_norm || q_norm.contains(&k_norm) || k_norm.contains(&q_norm) {
                return Some(entry.to_metadata());
            }
        }
    }

    None
}

impl CuratedMetaEntry {
    pub fn to_metadata(&self) -> GameMetadata {
        GameMetadata {
            display_name: Some(self.display_name.to_string()),
            release_year: Some(self.release_year),
            release_month: None,
            developer: Some(self.developer.to_string()),
            publisher: Some(self.publisher.to_string()),
            genre: Some(self.genre.to_string()),
            franchise: self.franchise.map(|f| f.to_string()),
            region: Some("Región Libre".to_string()),
            rating: None,
        }
    }
}
