use super::libretro::GameMetadata;

pub struct CuratedMetaEntry {
    pub platforms: &'static [&'static str],
    pub keys: &'static [&'static str],
    pub display_name: &'static str,
    pub genre: &'static str,
    pub developer: &'static str,
    pub publisher: &'static str,
    pub release_year: i32,
    pub franchise: Option<&'static str>,
}

pub static CURATED_CATALOG: &[CuratedMetaEntry] = &[
    // --- POKEMON CLÁSICOS (GB, GBC, GBA, NDS) ---
    CuratedMetaEntry {
        platforms: &["GB"],
        keys: &[
            "pokemon - edicion roja",
            "pokemon red",
            "pokemon - red version",
            "pokemon roja",
        ],
        display_name: "Pokémon Edición Roja",
        genre: "Rol / RPG",
        developer: "Game Freak",
        publisher: "Nintendo",
        release_year: 1996,
        franchise: Some("Pokemon"),
    },
    CuratedMetaEntry {
        platforms: &["GB"],
        keys: &[
            "pokemon - edicion azul",
            "pokemon blue",
            "pokemon - blue version",
            "pokemon azul",
        ],
        display_name: "Pokémon Edición Azul",
        genre: "Rol / RPG",
        developer: "Game Freak",
        publisher: "Nintendo",
        release_year: 1996,
        franchise: Some("Pokemon"),
    },
    CuratedMetaEntry {
        platforms: &["GBC"],
        keys: &[
            "pokemon - gold version",
            "pokemon gold",
            "pokemon oro",
            "pokemon - edicion oro",
        ],
        display_name: "Pokémon Edición Oro",
        genre: "Rol / RPG",
        developer: "Game Freak",
        publisher: "Nintendo",
        release_year: 1999,
        franchise: Some("Pokemon"),
    },
    CuratedMetaEntry {
        platforms: &["GBC"],
        keys: &[
            "pokemon - silver version",
            "pokemon silver",
            "pokemon plata",
            "pokemon - edicion plata",
        ],
        display_name: "Pokémon Edición Plata",
        genre: "Rol / RPG",
        developer: "Game Freak",
        publisher: "Nintendo",
        release_year: 1999,
        franchise: Some("Pokemon"),
    },
    CuratedMetaEntry {
        platforms: &["GBA"],
        keys: &[
            "pokemon - edicion esmeralda",
            "pokemon emerald",
            "pokemon esmeralda",
        ],
        display_name: "Pokémon Edición Esmeralda",
        genre: "Rol / RPG",
        developer: "Game Freak",
        publisher: "Nintendo",
        release_year: 2004,
        franchise: Some("Pokemon"),
    },
    CuratedMetaEntry {
        platforms: &["GBA"],
        keys: &["pokemon - edicion rubi", "pokemon ruby", "pokemon rubi"],
        display_name: "Pokémon Edición Rubí",
        genre: "Rol / RPG",
        developer: "Game Freak",
        publisher: "Nintendo",
        release_year: 2002,
        franchise: Some("Pokemon"),
    },
    CuratedMetaEntry {
        platforms: &["GBA"],
        keys: &[
            "pokemon - edicion zafiro",
            "pokemon sapphire",
            "pokemon zafiro",
        ],
        display_name: "Pokémon Edición Zafiro",
        genre: "Rol / RPG",
        developer: "Game Freak",
        publisher: "Nintendo",
        release_year: 2002,
        franchise: Some("Pokemon"),
    },
    CuratedMetaEntry {
        platforms: &["GBA"],
        keys: &[
            "pokemon - edicion rojo fuego",
            "pokemon firered",
            "pokemon rojo fuego",
        ],
        display_name: "Pokémon Edición Rojo Fuego",
        genre: "Rol / RPG",
        developer: "Game Freak",
        publisher: "Nintendo",
        release_year: 2004,
        franchise: Some("Pokemon"),
    },
    CuratedMetaEntry {
        platforms: &["GBA"],
        keys: &[
            "pokemon - edicion verde hoja",
            "pokemon leafgreen",
            "pokemon verde hoja",
        ],
        display_name: "Pokémon Edición Verde Hoja",
        genre: "Rol / RPG",
        developer: "Game Freak",
        publisher: "Nintendo",
        release_year: 2004,
        franchise: Some("Pokemon"),
    },
    CuratedMetaEntry {
        platforms: &["GBA"],
        keys: &[
            "pokemon mystery dungeon - red rescue team",
            "red rescue team",
            "equipo de rescate rojo",
        ],
        display_name: "Pokémon Mundo Misterioso: Equipo de Rescate Rojo",
        genre: "Rol / RPG",
        developer: "Spike Chunsoft",
        publisher: "Nintendo",
        release_year: 2005,
        franchise: Some("Pokemon"),
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &[
            "pokemon - edicion platino",
            "pokemon platinum",
            "pokemon platino",
        ],
        display_name: "Pokémon Edición Platino",
        genre: "Rol / RPG",
        developer: "Game Freak",
        publisher: "The Pokémon Company / Nintendo",
        release_year: 2008,
        franchise: Some("Pokemon"),
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &["pokemon conquest", "pokemon + nobunaga"],
        display_name: "Pokémon Conquest",
        genre: "Estrategia",
        developer: "Tecmo Koei",
        publisher: "The Pokémon Company / Nintendo",
        release_year: 2012,
        franchise: Some("Pokemon"),
    },
    CuratedMetaEntry {
        platforms: &["NDS"],
        keys: &[
            "dragon quest ix - sentinels of the starry skies",
            "dragon quest ix",
            "sentinels of the starry skies",
        ],
        display_name: "Dragon Quest IX: Centinelas del Firmamento",
        genre: "Rol / RPG",
        developer: "Level-5 / Square Enix",
        publisher: "Nintendo",
        release_year: 2009,
        franchise: Some("Dragon Quest"),
    },
    // --- GBA JOJAS ---
    CuratedMetaEntry {
        platforms: &["GBA"],
        keys: &["advance wars 2 - black hole rising", "advance wars 2"],
        display_name: "Advance Wars 2: Black Hole Rising",
        genre: "Estrategia",
        developer: "Intelligent Systems",
        publisher: "Nintendo",
        release_year: 2003,
        franchise: Some("Advance Wars"),
    },
    CuratedMetaEntry {
        platforms: &["GBA"],
        keys: &[
            "golden sun - the lost age",
            "golden sun 2",
            "la edad perdida",
        ],
        display_name: "Golden Sun: La Edad Perdida",
        genre: "Rol / RPG",
        developer: "Camelot Software Planning",
        publisher: "Nintendo",
        release_year: 2002,
        franchise: Some("Golden Sun"),
    },
    CuratedMetaEntry {
        platforms: &["GBA"],
        keys: &["golden sun"],
        display_name: "Golden Sun",
        genre: "Rol / RPG",
        developer: "Camelot Software Planning",
        publisher: "Nintendo",
        release_year: 2001,
        franchise: Some("Golden Sun"),
    },
    CuratedMetaEntry {
        platforms: &["GBA"],
        keys: &[
            "zelda - the minish cap",
            "the minish cap",
            "legend of zelda - the minish cap",
            "minish cap",
        ],
        display_name: "The Legend of Zelda: The Minish Cap",
        genre: "Aventura",
        developer: "Capcom / Flagship",
        publisher: "Nintendo",
        release_year: 2004,
        franchise: Some("The Legend of Zelda"),
    },
    CuratedMetaEntry {
        platforms: &["GBA"],
        keys: &["kingdom hearts - chain of memories", "chain of memories"],
        display_name: "Kingdom Hearts: Chain of Memories",
        genre: "Rol / RPG",
        developer: "Jupiter / Square Enix",
        publisher: "Square Enix",
        release_year: 2004,
        franchise: Some("Kingdom Hearts"),
    },
    CuratedMetaEntry {
        platforms: &["GBA"],
        keys: &[
            "kirby & the amazing mirror",
            "the amazing mirror",
            "amazing mirror",
            "kirby el laberinto de los espejos",
        ],
        display_name: "Kirby & The Amazing Mirror",
        genre: "Plataformas",
        developer: "HAL Laboratory / Flagship",
        publisher: "Nintendo",
        release_year: 2004,
        franchise: Some("Kirby"),
    },
    CuratedMetaEntry {
        platforms: &["GBA"],
        keys: &[
            "mario kart - super circuit",
            "super circuit",
            "mario kart super circuit",
        ],
        display_name: "Mario Kart: Super Circuit",
        genre: "Carreras",
        developer: "Intelligent Systems",
        publisher: "Nintendo",
        release_year: 2001,
        franchise: Some("Mario Kart"),
    },
    CuratedMetaEntry {
        platforms: &["GBA"],
        keys: &["castlevania - aria of sorrow", "aria of sorrow"],
        display_name: "Castlevania: Aria of Sorrow",
        genre: "Rol / RPG",
        developer: "Konami Computer Entertainment Tokyo",
        publisher: "Konami",
        release_year: 2003,
        franchise: Some("Castlevania"),
    },
    CuratedMetaEntry {
        platforms: &["GBA"],
        keys: &[
            "castlevania - harmony of dissonance",
            "harmony of dissonance",
        ],
        display_name: "Castlevania: Harmony of Dissonance",
        genre: "Rol / RPG",
        developer: "Konami Computer Entertainment Tokyo",
        publisher: "Konami",
        release_year: 2002,
        franchise: Some("Castlevania"),
    },
    CuratedMetaEntry {
        platforms: &["GBA"],
        keys: &["final fantasy tactics advance", "tactics advance"],
        display_name: "Final Fantasy Tactics Advance",
        genre: "Estrategia",
        developer: "Square Enix",
        publisher: "Square Enix / Nintendo",
        release_year: 2003,
        franchise: Some("Final Fantasy"),
    },
    CuratedMetaEntry {
        platforms: &["GBA"],
        keys: &[
            "fire emblem - the sacred stones",
            "the sacred stones",
            "sacred stones",
        ],
        display_name: "Fire Emblem: The Sacred Stones",
        genre: "Estrategia",
        developer: "Intelligent Systems",
        publisher: "Nintendo",
        release_year: 2004,
        franchise: Some("Fire Emblem"),
    },
    CuratedMetaEntry {
        platforms: &["GBA"],
        keys: &[
            "fire emblem - fuuin no tsurugi",
            "fuuin no tsurugi",
            "binding blade",
        ],
        display_name: "Fire Emblem: The Binding Blade",
        genre: "Estrategia",
        developer: "Intelligent Systems",
        publisher: "Nintendo",
        release_year: 2002,
        franchise: Some("Fire Emblem"),
    },
    CuratedMetaEntry {
        platforms: &["GBA"],
        keys: &["boktai - the sun is in your hand", "boktai"],
        display_name: "Boktai: The Sun Is in Your Hand",
        genre: "Aventura",
        developer: "Konami Computer Entertainment Japan",
        publisher: "Konami",
        release_year: 2003,
        franchise: Some("Boktai"),
    },
    CuratedMetaEntry {
        platforms: &["GBA"],
        keys: &["boktai 2 - solar boy django", "boktai 2"],
        display_name: "Boktai 2: Solar Boy Django",
        genre: "Aventura",
        developer: "Konami Computer Entertainment Japan",
        publisher: "Konami",
        release_year: 2004,
        franchise: Some("Boktai"),
    },
    CuratedMetaEntry {
        platforms: &["GBA"],
        keys: &["beyblade g-revolution", "beyblade g revolution"],
        display_name: "Beyblade G-Revolution",
        genre: "Acción / Lucha",
        developer: "SIMS",
        publisher: "Atari",
        release_year: 2004,
        franchise: Some("Beyblade"),
    },
    CuratedMetaEntry {
        platforms: &["GBA"],
        keys: &[
            "beyblade v-force - ultimate blader jam",
            "beyblade v-force",
            "beyblade v force",
        ],
        display_name: "Beyblade V-Force: Ultimate Blader Jam",
        genre: "Acción",
        developer: "Natsume",
        publisher: "Atari",
        release_year: 2003,
        franchise: Some("Beyblade"),
    },
    // --- SNES CLÁSICOS ---
    CuratedMetaEntry {
        platforms: &["SNES"],
        keys: &[
            "super metroid",
            "super metroid (europe)",
            "super metroid (usa)",
        ],
        display_name: "Super Metroid",
        genre: "Acción",
        developer: "Nintendo R&D1 / Intelligent Systems",
        publisher: "Nintendo",
        release_year: 1994,
        franchise: Some("Metroid"),
    },
    CuratedMetaEntry {
        platforms: &["SNES"],
        keys: &["chrono trigger"],
        display_name: "Chrono Trigger",
        genre: "Rol / RPG",
        developer: "SquareSoft",
        publisher: "SquareSoft",
        release_year: 1995,
        franchise: Some("Chrono"),
    },
    CuratedMetaEntry {
        platforms: &["SNES"],
        keys: &[
            "donkey kong country 2 - diddy's kong quest",
            "donkey kong country 2",
            "diddy's kong quest",
        ],
        display_name: "Donkey Kong Country 2: Diddy's Kong Quest",
        genre: "Plataformas",
        developer: "Rare Ltd.",
        publisher: "Nintendo",
        release_year: 1995,
        franchise: Some("Donkey Kong"),
    },
    CuratedMetaEntry {
        platforms: &["SNES"],
        keys: &[
            "donkey kong country 3 - dixie kong's double trouble!",
            "donkey kong country 3",
            "dixie kong's double trouble",
        ],
        display_name: "Donkey Kong Country 3: Dixie Kong's Double Trouble!",
        genre: "Plataformas",
        developer: "Rare Ltd.",
        publisher: "Nintendo",
        release_year: 1996,
        franchise: Some("Donkey Kong"),
    },
    CuratedMetaEntry {
        platforms: &["SNES"],
        keys: &["donkey kong country", "super donkey kong"],
        display_name: "Donkey Kong Country",
        genre: "Plataformas",
        developer: "Rare Ltd.",
        publisher: "Nintendo",
        release_year: 1994,
        franchise: Some("Donkey Kong"),
    },
    CuratedMetaEntry {
        platforms: &["SNES"],
        keys: &["earthbound", "mother 2"],
        display_name: "EarthBound",
        genre: "Rol / RPG",
        developer: "Ape / HAL Laboratory",
        publisher: "Nintendo",
        release_year: 1994,
        franchise: Some("Mother / EarthBound"),
    },
    CuratedMetaEntry {
        platforms: &["SNES"],
        keys: &["super mario world 2 - yoshi's island", "yoshi's island"],
        display_name: "Super Mario World 2: Yoshi's Island",
        genre: "Plataformas",
        developer: "Nintendo EAD",
        publisher: "Nintendo",
        release_year: 1995,
        franchise: Some("Mario"),
    },
    CuratedMetaEntry {
        platforms: &["SNES"],
        keys: &["super mario world"],
        display_name: "Super Mario World",
        genre: "Plataformas",
        developer: "Nintendo EAD",
        publisher: "Nintendo",
        release_year: 1990,
        franchise: Some("Mario"),
    },
    CuratedMetaEntry {
        platforms: &["SNES"],
        keys: &[
            "super mario rpg - legend of the seven stars",
            "super mario rpg",
            "legend of the seven stars",
        ],
        display_name: "Super Mario RPG: Legend of the Seven Stars",
        genre: "Rol / RPG",
        developer: "SquareSoft / Nintendo",
        publisher: "Nintendo",
        release_year: 1996,
        franchise: Some("Mario"),
    },
    CuratedMetaEntry {
        platforms: &["SNES"],
        keys: &[
            "legend of zelda, the - a link to the past",
            "a link to the past",
            "link to the past",
        ],
        display_name: "The Legend of Zelda: A Link to the Past",
        genre: "Aventura",
        developer: "Nintendo EAD",
        publisher: "Nintendo",
        release_year: 1991,
        franchise: Some("The Legend of Zelda"),
    },
    CuratedMetaEntry {
        platforms: &["SNES"],
        keys: &["secret of mana", "seiken densetsu 2"],
        display_name: "Secret of Mana",
        genre: "Rol / RPG",
        developer: "SquareSoft",
        publisher: "SquareSoft",
        release_year: 1993,
        franchise: Some("Mana"),
    },
    CuratedMetaEntry {
        platforms: &["SNES"],
        keys: &["secret of evermore"],
        display_name: "Secret of Evermore",
        genre: "Rol / RPG",
        developer: "SquareSoft",
        publisher: "SquareSoft",
        release_year: 1995,
        franchise: None,
    },
    CuratedMetaEntry {
        platforms: &["SNES"],
        keys: &["terranigma"],
        display_name: "Terranigma",
        genre: "Rol / RPG",
        developer: "Quintet",
        publisher: "Enix / Nintendo",
        release_year: 1995,
        franchise: None,
    },
    CuratedMetaEntry {
        platforms: &["SNES"],
        keys: &["illusion of time", "illusion of gaia"],
        display_name: "Illusion of Time",
        genre: "Rol / RPG",
        developer: "Quintet",
        publisher: "Enix / Nintendo",
        release_year: 1993,
        franchise: None,
    },
    CuratedMetaEntry {
        platforms: &["SNES"],
        keys: &["mega man x3", "megaman x3"],
        display_name: "Mega Man X3",
        genre: "Acción",
        developer: "Capcom",
        publisher: "Capcom",
        release_year: 1995,
        franchise: Some("Mega Man"),
    },
    CuratedMetaEntry {
        platforms: &["SNES"],
        keys: &["mega man x2", "megaman x2"],
        display_name: "Mega Man X2",
        genre: "Acción",
        developer: "Capcom",
        publisher: "Capcom",
        release_year: 1994,
        franchise: Some("Mega Man"),
    },
    CuratedMetaEntry {
        platforms: &["SNES"],
        keys: &["mega man x", "megaman x"],
        display_name: "Mega Man X",
        genre: "Acción",
        developer: "Capcom",
        publisher: "Capcom",
        release_year: 1993,
        franchise: Some("Mega Man"),
    },
    CuratedMetaEntry {
        platforms: &["SNES"],
        keys: &["castlevania - dracula x", "dracula x"],
        display_name: "Castlevania: Dracula X",
        genre: "Plataformas",
        developer: "Konami",
        publisher: "Konami",
        release_year: 1995,
        franchise: Some("Castlevania"),
    },
    CuratedMetaEntry {
        platforms: &["SNES"],
        keys: &[
            "turtles in time",
            "teenage mutant ninja turtles iv - turtles in time",
        ],
        display_name: "TMNT IV: Turtles in Time",
        genre: "Acción",
        developer: "Konami",
        publisher: "Konami",
        release_year: 1992,
        franchise: Some("TMNT"),
    },
    // --- PLAYSTATION 1 & 2 ---
    CuratedMetaEntry {
        platforms: &["PS1"],
        keys: &["metal gear solid", "mgs"],
        display_name: "Metal Gear Solid",
        genre: "Acción",
        developer: "Konami Computer Entertainment Japan",
        publisher: "Konami",
        release_year: 1998,
        franchise: Some("Metal Gear"),
    },
    CuratedMetaEntry {
        platforms: &["PS1"],
        keys: &[
            "castlevania - symphony of the night",
            "symphony of the night",
        ],
        display_name: "Castlevania: Symphony of the Night",
        genre: "Rol / RPG",
        developer: "Konami Computer Entertainment Tokyo",
        publisher: "Konami",
        release_year: 1997,
        franchise: Some("Castlevania"),
    },
    CuratedMetaEntry {
        platforms: &["PS1"],
        keys: &[
            "the legend of the dragoon",
            "legend of the dragoon",
            "legend of dragoon",
        ],
        display_name: "The Legend of Dragoon",
        genre: "Rol / RPG",
        developer: "Sony Computer Entertainment Japan",
        publisher: "Sony Computer Entertainment",
        release_year: 1999,
        franchise: Some("The Legend of Dragoon"),
    },
    CuratedMetaEntry {
        platforms: &["PS1"],
        keys: &["vagrant story"],
        display_name: "Vagrant Story",
        genre: "Rol / RPG",
        developer: "SquareSoft",
        publisher: "SquareSoft",
        release_year: 2000,
        franchise: None,
    },
    CuratedMetaEntry {
        platforms: &["PS1"],
        keys: &["xenogears"],
        display_name: "Xenogears",
        genre: "Rol / RPG",
        developer: "SquareSoft",
        publisher: "SquareSoft",
        release_year: 1998,
        franchise: Some("Xeno"),
    },
    CuratedMetaEntry {
        platforms: &["PS1"],
        keys: &["chrono cross"],
        display_name: "Chrono Cross",
        genre: "Rol / RPG",
        developer: "SquareSoft",
        publisher: "SquareSoft",
        release_year: 1999,
        franchise: Some("Chrono"),
    },
    CuratedMetaEntry {
        platforms: &["PS1"],
        keys: &["breath of fire iv", "breath of fire 4"],
        display_name: "Breath of Fire IV",
        genre: "Rol / RPG",
        developer: "Capcom",
        publisher: "Capcom",
        release_year: 2000,
        franchise: Some("Breath of Fire"),
    },
    CuratedMetaEntry {
        platforms: &["PS1"],
        keys: &["digimon world 2003", "digimon world 3"],
        display_name: "Digimon World 2003",
        genre: "Rol / RPG",
        developer: "Bandai",
        publisher: "Bandai",
        release_year: 2002,
        franchise: Some("Digimon"),
    },
    // --- PS2 ---
    CuratedMetaEntry {
        platforms: &["PS2"],
        keys: &["shadow of the colossus"],
        display_name: "Shadow of the Colossus",
        genre: "Acción / Aventura",
        developer: "Team Ico",
        publisher: "Sony Computer Entertainment",
        release_year: 2005,
        franchise: Some("Ico"),
    },
    CuratedMetaEntry {
        platforms: &["PS2"],
        keys: &["ico"],
        display_name: "Ico",
        genre: "Aventura / Puzle",
        developer: "Team Ico",
        publisher: "Sony Computer Entertainment",
        release_year: 2001,
        franchise: Some("Ico"),
    },
    CuratedMetaEntry {
        platforms: &["PS2"],
        keys: &["god of war ii", "god of war 2"],
        display_name: "God of War II",
        genre: "Acción / Hack and Slash",
        developer: "Santa Monica Studio",
        publisher: "Sony Computer Entertainment",
        release_year: 2007,
        franchise: Some("God of War"),
    },
    CuratedMetaEntry {
        platforms: &["PS2"],
        keys: &["god of war"],
        display_name: "God of War",
        genre: "Acción / Hack and Slash",
        developer: "Santa Monica Studio",
        publisher: "Sony Computer Entertainment",
        release_year: 2005,
        franchise: Some("God of War"),
    },
    CuratedMetaEntry {
        platforms: &["PS2"],
        keys: &[
            "grand theft auto - san andreas",
            "gta san andreas",
            "grand theft auto san andreas",
        ],
        display_name: "Grand Theft Auto: San Andreas",
        genre: "Acción / Sandbox",
        developer: "Rockstar North",
        publisher: "Rockstar Games",
        release_year: 2004,
        franchise: Some("Grand Theft Auto"),
    },
    CuratedMetaEntry {
        platforms: &["PS2"],
        keys: &["silent hill 2"],
        display_name: "Silent Hill 2",
        genre: "Terror / Supervivencia",
        developer: "Team Silent",
        publisher: "Konami",
        release_year: 2001,
        franchise: Some("Silent Hill"),
    },
    CuratedMetaEntry {
        platforms: &["PS2"],
        keys: &["metal gear solid 3 - snake eater", "metal gear solid 3"],
        display_name: "Metal Gear Solid 3: Snake Eater",
        genre: "Sigilo / Acción",
        developer: "Konami Computer Entertainment Japan",
        publisher: "Konami",
        release_year: 2004,
        franchise: Some("Metal Gear"),
    },
    CuratedMetaEntry {
        platforms: &["PS2"],
        keys: &["the king of fighters xi", "king of fighters xi", "kof xi"],
        display_name: "The King of Fighters XI",
        genre: "Lucha",
        developer: "SNK Playmore",
        publisher: "SNK Playmore",
        release_year: 2005,
        franchise: Some("The King of Fighters"),
    },
    // --- PSP ---
    CuratedMetaEntry {
        platforms: &["PSP"],
        keys: &["patapon 3"],
        display_name: "Patapon 3",
        genre: "Ritmo / Música",
        developer: "Pyramid / Japan Studio",
        publisher: "Sony Computer Entertainment",
        release_year: 2011,
        franchise: Some("Patapon"),
    },
    CuratedMetaEntry {
        platforms: &["PSP"],
        keys: &["patapon 2"],
        display_name: "Patapon 2",
        genre: "Ritmo / Música",
        developer: "Pyramid / Japan Studio",
        publisher: "Sony Computer Entertainment",
        release_year: 2008,
        franchise: Some("Patapon"),
    },
    CuratedMetaEntry {
        platforms: &["PSP"],
        keys: &["patapon"],
        display_name: "Patapon",
        genre: "Ritmo / Música",
        developer: "Pyramid / Japan Studio",
        publisher: "Sony Computer Entertainment",
        release_year: 2007,
        franchise: Some("Patapon"),
    },
    CuratedMetaEntry {
        platforms: &["PSP"],
        keys: &["locoroco 2"],
        display_name: "LocoRoco 2",
        genre: "Plataformas",
        developer: "Japan Studio",
        publisher: "Sony Computer Entertainment",
        release_year: 2008,
        franchise: Some("LocoRoco"),
    },
    CuratedMetaEntry {
        platforms: &["PSP"],
        keys: &["locoroco"],
        display_name: "LocoRoco",
        genre: "Plataformas",
        developer: "Japan Studio",
        publisher: "Sony Computer Entertainment",
        release_year: 2006,
        franchise: Some("LocoRoco"),
    },
    CuratedMetaEntry {
        platforms: &["PSP"],
        keys: &[
            "dissidia 012 - duodecim final fantasy",
            "dissidia 012",
            "duodecim",
        ],
        display_name: "Dissidia 012: Duodecim Final Fantasy",
        genre: "Lucha",
        developer: "Square Enix",
        publisher: "Square Enix",
        release_year: 2011,
        franchise: Some("Final Fantasy"),
    },
    CuratedMetaEntry {
        platforms: &["PSP"],
        keys: &["wizorb"],
        display_name: "Wizorb",
        genre: "Puzle / Breakout",
        developer: "Tribute Games",
        publisher: "Tribute Games",
        release_year: 2011,
        franchise: None,
    },
    // --- PS3 ---
    CuratedMetaEntry {
        platforms: &["PS3"],
        keys: &["dragon's crown", "dragons crown"],
        display_name: "Dragon's Crown",
        genre: "Acción / Rol",
        developer: "Vanillaware",
        publisher: "Atlus",
        release_year: 2013,
        franchise: None,
    },
    CuratedMetaEntry {
        platforms: &["PS3"],
        keys: &["god of war collection"],
        display_name: "God of War Collection",
        genre: "Acción / Hack and Slash",
        developer: "Bluepoint Games",
        publisher: "Sony Computer Entertainment",
        release_year: 2009,
        franchise: Some("God of War"),
    },
    // --- GAMECUBE ---
    CuratedMetaEntry {
        platforms: &["GAMECUBE", "GameCube", "NGC"],
        keys: &[
            "mario kart - double dash!!",
            "mario kart double dash",
            "mario kart - double dash",
        ],
        display_name: "Mario Kart: Double Dash!!",
        genre: "Carreras",
        developer: "Nintendo EAD",
        publisher: "Nintendo",
        release_year: 2003,
        franchise: Some("Mario Kart"),
    },
    CuratedMetaEntry {
        platforms: &["GAMECUBE", "GameCube", "NGC"],
        keys: &[
            "the legend of zelda - the wind waker",
            "legend of zelda, the - the wind waker",
            "wind waker",
        ],
        display_name: "The Legend of Zelda: The Wind Waker",
        genre: "Aventura / Acción",
        developer: "Nintendo EAD",
        publisher: "Nintendo",
        release_year: 2002,
        franchise: Some("The Legend of Zelda"),
    },
    CuratedMetaEntry {
        platforms: &["GAMECUBE", "GameCube", "NGC"],
        keys: &["metroid prime"],
        display_name: "Metroid Prime",
        genre: "Acción / Aventura",
        developer: "Retro Studios",
        publisher: "Nintendo",
        release_year: 2002,
        franchise: Some("Metroid"),
    },
    CuratedMetaEntry {
        platforms: &["GAMECUBE", "GameCube", "NGC"],
        keys: &["super smash bros. melee", "smash bros melee", "melee"],
        display_name: "Super Smash Bros. Melee",
        genre: "Lucha",
        developer: "HAL Laboratory",
        publisher: "Nintendo",
        release_year: 2001,
        franchise: Some("Super Smash Bros."),
    },
    CuratedMetaEntry {
        platforms: &["GAMECUBE", "GameCube", "NGC"],
        keys: &["mario party 7"],
        display_name: "Mario Party 7",
        genre: "Party / Minijuegos",
        developer: "Hudson Soft",
        publisher: "Nintendo",
        release_year: 2005,
        franchise: Some("Mario Party"),
    },
    // --- MEGA DRIVE & SMS ---
    CuratedMetaEntry {
        platforms: &["MEGA_DRIVE"],
        keys: &["sonic the hedgehog 3", "sonic 3"],
        display_name: "Sonic The Hedgehog 3",
        genre: "Plataformas",
        developer: "Sonic Team",
        publisher: "Sega",
        release_year: 1994,
        franchise: Some("Sonic The Hedgehog"),
    },
    CuratedMetaEntry {
        platforms: &["MEGA_DRIVE"],
        keys: &["sonic the hedgehog 2", "sonic 2"],
        display_name: "Sonic The Hedgehog 2",
        genre: "Plataformas",
        developer: "Sega Technical Institute",
        publisher: "Sega",
        release_year: 1992,
        franchise: Some("Sonic The Hedgehog"),
    },
    CuratedMetaEntry {
        platforms: &["MEGA_DRIVE"],
        keys: &["sonic the hedgehog", "sonic 1"],
        display_name: "Sonic The Hedgehog",
        genre: "Plataformas",
        developer: "Sonic Team",
        publisher: "Sega",
        release_year: 1991,
        franchise: Some("Sonic The Hedgehog"),
    },
    CuratedMetaEntry {
        platforms: &["MEGA_DRIVE"],
        keys: &["gunstar heroes"],
        display_name: "Gunstar Heroes",
        genre: "Acción",
        developer: "Treasure",
        publisher: "Sega",
        release_year: 1993,
        franchise: None,
    },
    CuratedMetaEntry {
        platforms: &["SMS"],
        keys: &["alex kidd in miracle world"],
        display_name: "Alex Kidd in Miracle World",
        genre: "Plataformas",
        developer: "Sega",
        publisher: "Sega",
        release_year: 1986,
        franchise: Some("Alex Kidd"),
    },
    CuratedMetaEntry {
        platforms: &["SMS"],
        keys: &["alex kidd in shinobi world"],
        display_name: "Alex Kidd in Shinobi World",
        genre: "Plataformas",
        developer: "Sega",
        publisher: "Sega",
        release_year: 1990,
        franchise: Some("Alex Kidd"),
    },
    CuratedMetaEntry {
        platforms: &["SMS"],
        keys: &["golden axe warrior"],
        display_name: "Golden Axe Warrior",
        genre: "Aventura",
        developer: "Sega",
        publisher: "Sega",
        release_year: 1991,
        franchise: Some("Golden Axe"),
    },
    CuratedMetaEntry {
        platforms: &["SMS"],
        keys: &["line of fire"],
        display_name: "Line of Fire",
        genre: "Shooter / Disparos",
        developer: "Sega",
        publisher: "Sega",
        release_year: 1991,
        franchise: None,
    },
];

pub fn find_curated_catalog_metadata(query: &str, platform: &str) -> Option<GameMetadata> {
    let q_lower = query.to_lowercase();
    let q_clean = q_lower
        .split(" (")
        .next()
        .unwrap_or(&q_lower)
        .split(" [")
        .next()
        .unwrap_or(&q_lower)
        .trim();

    for entry in CURATED_CATALOG {
        if !entry
            .platforms
            .iter()
            .any(|&p| p.eq_ignore_ascii_case(platform))
        {
            continue;
        }

        for key in entry.keys {
            if q_clean == *key || q_clean.starts_with(key) || key.starts_with(q_clean) {
                return Some(entry.to_metadata());
            }
        }
    }

    None
}

impl CuratedMetaEntry {
    pub fn to_metadata(&self) -> GameMetadata {
        GameMetadata {
            display_name: Some(self.display_name.to_string()),
            release_year: Some(self.release_year),
            release_month: None,
            developer: Some(self.developer.to_string()),
            publisher: Some(self.publisher.to_string()),
            genre: Some(self.genre.to_string()),
            franchise: self.franchise.map(|f| f.to_string()),
            region: Some("Región Libre".to_string()),
            rating: None,
        }
    }
}
